### ISSUE TITLE
Using trellis quantization without other options is tricky

### ISSUE THREAD

**Issue by pornel** [mozilla/mozjpeg#111]
Background: I'm trying to compress images at a specific DSSIM quality, and for that I need to try a few different JPEG quality levels, as quickly as possible.

I wanted to enable trellis quantization (because it visibly affects the output), but disable all other slow optimizations, since I don't look at the file size when only measuring quality.

However, using just trellis is tricky and I didn't find documentation for it.

I've tried:

```c
jpeg_set_defaults(&cinfo);
jpeg_c_set_bool_param(&cinfo, JBOOLEAN_OPTIMIZE_SCANS, FALSE);
cinfo.optimize_coding = FALSE;
```

but there appears to be non-obvious coupling between trellis and progressive scan optimization:

> Invalid progressive parameters at scan script entry 4

An alternative approach doesn't work either:

```c
jpeg_c_set_bool_param(&cinfo, JBOOLEAN_USE_MOZ_DEFAULTS, FALSE); 
jpeg_set_defaults(&cinfo);
jpeg_c_set_bool_param(&cinfo, JBOOLEAN_TRELLIS_QUANT, TRUE);
```

> Bogus buffer control mode

I think the current settings are too low-level and don't hide implementation details of the library. I shouldn't be required to know that one setting depends on some other, seemingly unrelated settings. Flipping a single option on or off should do just that — not crash the library.

So if I just execute `jpeg_c_set_bool_param(&cinfo, JBOOLEAN_TRELLIS_QUANT, TRUE)` I expect that to automatically enable everything that trellis depends on behind the scenes, and not crash.

**Comment by bdaehlie** [comment]
@pornel Is there still an issue here?

**Comment by pornel** [comment]
I got used to it, so it's not a pain point for me any more.
