### ISSUE TITLE
PNG support disabled in Windows binaries?

### ISSUE THREAD

**Issue by hoon** [mozilla/mozjpeg#144]
The Windows binaries generated from the 3.0 release source by following the instructions in BUILDING.txt does not appear to have PNG support enabled.

When a PNG file is passed as input to `cjpeg.exe`, the following error message is displayed:
`Unrecognized input file format --- perhaps you need -targa`

I have manually compiled libpng and modified INCLUDE and LIBPATH, but that did not enable PNG support.

I have also tried manually editing `jconfig.h` to set `PNG_SUPPORTED` macro, but this approach did not work either.

**Comment by CoolOppo** [comment]
I'll give it a try with my binaries on Windows and get back to you with whether or not it worked for me.

**Comment by CoolOppo** [comment]
Alright, same thing:

```batch
cjpeg-static.exe -outfile test.jpg C:\Users\Me\Desktop\OPII0Rd.png
Unrecognized input file format --- perhaps you need -targa
```

By the way, I don't ever remember there being any support for PNG anyways with `mozjpeg`. I would recommend just encoding the JPEG with something like ImageMagick and then using `mozjpeg`'s `jpegtran` to optimize it. I do understand why it is frustrating though because nobody really wants to pull in another entire toolchain just to encode a JPEG from a PNG file, but it honestly shouldn't be too big of a deal on any platform people are using right now since ImageMagick is supported almost everywhere.

**Comment by dwbuiten** [comment]
Indeed it looks like the cmake build system doesn't expose (or support?) the libpng checks.

However, the better idea would probably be to use ImageMagick or something with a build of mozjpeg that has stuff enabled by default. My 2 cents.

**Comment by CoolOppo** [comment]
> use...something with a build of mozjpeg that has stuff enabled by default

Well, that's really not a solution at all. Regardless, where can we even find a "something"?

**Comment by hoon** [comment]
@dwbuiten This bug probably doesn't affect people using the pre-3.0 workflow (use ImageMagick to output to Targa and pipe to cjpeg), but the release note for 3.0 does indicate direct PNG input support. 

Ideally, the build scripts would be fixed, but at the very least, the release note should be amended.

I'm a new user to mozjpeg, and it took me a while to figure out what was going on when the PNG direct input commands that I saw on Kornel Lesiński's widely read blog post (http://calendar.perfplanet.com/2014/mozjpeg-3-0/) didn't work.

**Comment by dwbuiten** [comment]
> Well, that's really not a solution at all. Regardless, where can we even find a "something"?

I think you probably misunderstood my intentions. PNG input should be fixed on Windows in the cmake build system. I'll try and submit a patch to fix this sometime soon.

I just meant the vast majority of people are still better off using mozjpeg via ImageMagick, since that's likely what their old workflow used, instead of a special toolchain just for jpeg (`cjpeg`).

**Comment by CoolOppo** [comment]
@dwbuiten You're right; I misunderstood.

**Comment by Zeokat** [comment]
I have the same problem, can't process PNG images with mozjpeg 3. I hope that PNG input will be added, it's very usefull.

Thanks.

**Comment by JosePineiro** [comment]
The same problem with mozjpeg v 3.1

**Comment by pornel** [comment]
[libjpeg-turbo may drop autotools](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/56). That should make Windows and non-Windows builds more consistent.

**Comment by piotr-cz** [comment]
Same problem in version 3.1 (build 20150904)

**Comment by DeeDeeG** [comment]
Folks are talking about this issue on a compression forum: https://encode.ru/threads/1892-mozjpeg/page3?s=95ba320be9082e2043bd367eafe1a456

They have a fix there it seems. Maybe someone from there can contribute their fix, or it can be reviewed and manually re-implemented?

**Comment by pornel** [comment]
PR would be welcome. 

One problem is that the fix from the encode.ru forum makes libpng *required* to build mozjpeg. It should be optional, like in the autotools version.

**Comment by polarathene** [comment]
Is the CMake config for this [CMakeLists.txt](https://github.com/mozilla/mozjpeg/blob/master/CMakeLists.txt)?(I'm not all that familiar with CMake)

I see the `PNG_SUPPORTED` variable only in conditionals for win32 and static builds? So CMake is unable to support this for Linux if libpng is available on the system? With mozjpeg moving to CMake only for next release, will this get resolved? (I'm attempting to build in Alpine, which is working fine but can't seem to enable the PNG support).

**Comment by kornelski** [comment]
It's possible that the new CMake from libjpeg-turbo 2.0 broke PNG support. Can you test it and report what exactly needs to be fixed?

**Comment by polarathene** [comment]
@kornelski Isn't the PNG support optional at compile? I don't know much about compiling projects like this, I'm not all that familiar with the tools. `CMakeLists.txt` only mentions the PNG support within conditionals for win32 and static builds? 

I am building on an alpine linux image like this:

```Dockerfile
RUN cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 .. \
  && make install prefix=/usr/local libdir=/usr/local/lib64
```

and in a debian docker image:

```Dockerfile
RUN cmake -G"Unix Makefiles" .. \
  && make install
```
