### ISSUE TITLE
make test fails in several ways

### ISSUE THREAD

**Issue by davidfavor** [mozilla/mozjpeg#157]
Using latest git pull + latest Ubuntu + latest mainline ppa kernel...

net3# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

net3# uname -a
Linux net3.bizcooker.com 3.18.4-031804-generic #201501271243 SMP Tue Jan 27 17:45:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The - make test - step ran for hours + croaked with...

Buffer size regression test
TurboJPEG ERROR:
DCT coefficient out of range
Makefile:2481: recipe for target 'test' failed
make: *** [test] Error 255

This seems to relate to libturbojpeg, so here are the related packages that are installed.

net3# pkg-list | grep -i turbo
libjpeg-turbo-progs                               1.3.0-0ubuntu2
libjpeg-turbo-test                                1.3.0-0ubuntu2
libjpeg-turbo8                                    1.3.0-0ubuntu2
libjpeg-turbo8-dbg                                1.3.0-0ubuntu2
libjpeg-turbo8-dev                                1.3.0-0ubuntu2
libturbojpeg                                      1.3.0-0ubuntu2

Any suggestions debugging this?

**Comment by fbossen** [comment]
This appears to be related to the overshoot_deringing parameter. Will further look into it.
