### ISSUE TITLE
STDIN/STDOUT with other flags

### ISSUE THREAD

**Issue by ryanrussell** [mozilla/mozjpeg#158]
Hi,

I'm able to get stdin/out working just fine with mozjpeg if I just run without any flags. 
Example(Python):
subp = subprocess.Popen(["/home/ubuntu/mozjpeg/cjpeg"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        image_results = subp.communicate(input=out_im2.getvalue())

If, however, I attempt to customize this with flags(For example "-quality 70"), I cannot get it to work. I'm not sure if this is a bug or if I'm missing something. Any insight would be greatly appreciated:

subp = subprocess.Popen(["/home/ubuntu/mozjpeg/cjpeg", "-quality 70"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
image_results = subp.communicate(input=out_im2.getvalue())

Output is:
/home/ubuntu/mozjpeg/.libs/lt-cjpeg: unknown option 'quality 70'
usage: /home/ubuntu/mozjpeg/.libs/lt-cjpeg [switches] [inputfile]
Switches (names may be abbreviated):
  -quality N[,...]   Compression quality (0..100; 5-95 is useful range)
.... <Rest of --help screen>

Thanks in advance for any help.

**Comment by njdoyle** [comment]
“-quality 70” should be “-quality”, “70”. Two parameters.

**Comment by ryanrussell** [comment]
Thanks Nick! You da man
