### ISSUE TITLE
Latest commit (fbf0a5f) fails to build on Linux

### ISSUE THREAD

**Issue by DrYak** [mozilla/mozjpeg#160]
I'm trying to build myself a version of mozjpeg to play around with.

Compile fails:
* `setmode()` doesn't make any sense on system that don't make distinction between _binary_ and _text_ modes (most non-Windows OSes)
* maths functions used by the arithmetic coder need explicit linking to the libM

here is my patch (GitHub issue editor refuses do attach it):

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1f2e5f5..7ef0be9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -53,6 +53,13 @@ option(WITH_MEM_SRCDST "Include in-memory source/destination manager functions w
 option(WITH_TURBOJPEG "Include the TurboJPEG wrapper library and associated test programs" TRUE)
 option(WITH_JAVA "Build Java wrapper for the TurboJPEG library" FALSE)
 option(WITH_12BIT "Encode/decode JPEG images with 12-bit samples (implies WITH_SIMD=0 WITH_TURBOJPEG=0 WITH_ARITH_ENC=0 WITH_ARITH_DEC=0)" FALSE)
+option(WITH_SETMODE "Enable using setmode to switch from text to binary mode on platforms that make this distinction (WIN32)" WIN32)
+
+if (WITH_SETMODE)
+  set(SETMODE "-DSET_MODE")
+else()
+  set(SETMODE "")
+endif()
 
 if(WITH_12BIT)
   set(WITH_SIMD FALSE)
@@ -221,6 +228,9 @@ endif()
 add_subdirectory(sharedlib)
 
 add_library(jpeg-static STATIC ${JPEG_SOURCES} ${SIMD_OBJS})
+if(C_ARITH_CODING_SUPPORTED OR D_ARITH_CODING_SUPPORTED)
+  target_link_libraries(jpeg-static m)
+endif()
 if(NOT MSVC)
   set_target_properties(jpeg-static PROPERTIES OUTPUT_NAME jpeg)
 endif()
@@ -240,7 +250,10 @@ if(WITH_TURBOJPEG)
   if(MINGW)
     set_target_properties(turbojpeg PROPERTIES LINK_FLAGS -Wl,--kill-at)
   endif()
-  target_link_libraries(turbojpeg jpeg-static)
+  target_link_libraries(turbojpeg jpeg)
+  if(C_ARITH_CODING_SUPPORTED OR D_ARITH_CODING_SUPPORTED)
+    target_link_libraries(turbojpeg m)
+  endif()
   set_target_properties(turbojpeg PROPERTIES LINK_INTERFACE_LIBRARIES "")
 
   add_library(turbojpeg-static STATIC ${JPEG_SOURCES} ${SIMD_OBJS}
@@ -251,6 +264,9 @@ if(WITH_TURBOJPEG)
   if(WITH_SIMD)
     add_dependencies(turbojpeg-static simd)
   endif()
+  if(C_ARITH_CODING_SUPPORTED OR D_ARITH_CODING_SUPPORTED)
+    target_link_libraries(turbojpeg-static m)
+  endif()
 
   add_executable(tjunittest tjunittest.c tjutil.c)
   target_link_libraries(tjunittest turbojpeg)
@@ -272,9 +288,9 @@ if(WITH_TURBOJPEG)
 endif()
 
 if(WITH_12BIT)
-  set(COMPILE_FLAGS "-DGIF_SUPPORTED -DPPM_SUPPORTED -DUSE_SETMODE")
+  set(COMPILE_FLAGS "-DGIF_SUPPORTED -DPPM_SUPPORTED ${SETMODE}")
 else()
-  set(COMPILE_FLAGS "-DBMP_SUPPORTED -DGIF_SUPPORTED -DPPM_SUPPORTED -DTARGA_SUPPORTED -DUSE_SETMODE")
+  set(COMPILE_FLAGS "-DBMP_SUPPORTED -DGIF_SUPPORTED -DPPM_SUPPORTED -DTARGA_SUPPORTED ${SETMODE}")
 	set(CJPEG_BMP_SOURCES rdbmp.c rdtarga.c)
 	set(DJPEG_BMP_SOURCES wrbmp.c wrtarga.c)
 endif()
@@ -291,7 +307,7 @@ target_link_libraries(djpeg-static jpeg-static)
 
 add_executable(jpegtran-static jpegtran.c cdjpeg.c rdswitch.c transupp.c)
 target_link_libraries(jpegtran-static jpeg-static)
-set_property(TARGET jpegtran-static PROPERTY COMPILE_FLAGS "-DUSE_SETMODE")
+set_property(TARGET jpegtran-static PROPERTY COMPILE_FLAGS "${SETMODE}")
 
 add_executable(rdjpgcom rdjpgcom.c)
 
diff --git a/sharedlib/CMakeLists.txt b/sharedlib/CMakeLists.txt
index 268cc14..37793fc 100755
--- a/sharedlib/CMakeLists.txt
+++ b/sharedlib/CMakeLists.txt
@@ -31,6 +31,9 @@ else()
   add_library(jpeg SHARED ${JPEG_SRCS} ${SIMD_OBJS}
     "${CMAKE_SOURCE_DIR}/win/jpeg${DLL_VERSION}.def")
 endif()
+if(C_ARITH_CODING_SUPPORTED OR D_ARITH_CODING_SUPPORTED)
+  target_link_libraries(jpeg m)
+endif()
 set_target_properties(jpeg PROPERTIES SOVERSION ${DLL_VERSION}
   VERSION ${FULLVERSION})
 if(MSVC)
@@ -43,9 +46,9 @@ if(WITH_SIMD)
 endif()
 
 if(WITH_12BIT)
-  set(COMPILE_FLAGS "-DGIF_SUPPORTED -DPPM_SUPPORTED -DUSE_SETMODE")
+  set(COMPILE_FLAGS "-DGIF_SUPPORTED -DPPM_SUPPORTED ${SETMODE}")
 else()
-  set(COMPILE_FLAGS "-DBMP_SUPPORTED -DGIF_SUPPORTED -DPPM_SUPPORTED -DTARGA_SUPPORTED -DUSE_SETMODE")
+  set(COMPILE_FLAGS "-DBMP_SUPPORTED -DGIF_SUPPORTED -DPPM_SUPPORTED -DTARGA_SUPPORTED ${SETMODE}")
 	set(CJPEG_BMP_SOURCES ../rdbmp.c ../rdtarga.c)
 	set(DJPEG_BMP_SOURCES ../wrbmp.c ../wrtarga.c)
 endif()
@@ -62,7 +65,7 @@ target_link_libraries(djpeg jpeg)
 
 add_executable(jpegtran ../jpegtran.c ../cdjpeg.c ../rdswitch.c ../transupp.c)
 target_link_libraries(jpegtran jpeg)
-set_property(TARGET jpegtran PROPERTY COMPILE_FLAGS "-DUSE_SETMODE")
+set_property(TARGET jpegtran PROPERTY COMPILE_FLAGS "${SETMODE}")
 
 add_executable(jcstest ../jcstest.c)
 target_link_libraries(jcstest jpeg)
```

**Comment by lkwg82** [comment]
I tried it just now, and it runs fine.

**Comment by CoolOppo** [comment]
I have no issue building it at all. I just made a fresh copy of the repo and built it in less than two minutes on Ubuntu. It seems that the issue is on your end.

**Comment by lkwg82** [comment]
I just reverted to this specific version and I got it run.

Besides, please next time attach the error log and for the patch fork the project and request a pull request. It would have been some verification easier.

Cheers Lars

**Comment by DrYak** [comment]
> Besides, please next time attach the error log and for the patch fork the project and request a pull request.

Sorry. I'm new here. I opened my github account just a few minutes before posting. I'm more used to pass patch arround. Next time, I'll be using this.

> I have no issue building it at all. I just made a fresh copy of the repo and built it in less than two minutes on Ubuntu.

Actually (as it can be seen in the patch), the problem is when building using *cmake*. Autotools-based builds are okay. But I wasn't aware that cmake is only for non-Linux targets, and was using it. 
The problems I mention still persist today: SET_MODE is absent on unix platforms (it only makes sens on MS-DOS, Windows and Mac OS Classic which have different end-of-line markers) and -lm needs to be explicit.
Again, autotools build correctly on Linux. I presume Cmake builds correctly on Windows(?), only Cmake-on-Linux fails.

**Comment by pornel** [comment]
Everyone: please *do not use cmake on Linux*. The upstream libjpeg-turbo project **does not support cmake on linux**.

Linux build should be done only with autotools.

**Comment by lkwg82** [comment]
@DrYak Maybe you can pimp the manual at that point you trapped to use cmake?. ... and make a pull request ;)

Cheers Lars

**Comment by DrYak** [comment]
> Maybe you can pimp the manual at that point you trapped to use cmake?

Sorry, not native english speaker ; I fail to parse this part.

> and make a pull request ;)

You mean, a pull request for my "linux-ification" of the CMake scripts ?

**Comment by CoolOppo** [comment]
@DrYak When you "pimp" something (it's used as a verb here), it means that you are changing it for the better in some way. I think the term came from the television show "Pimp My Ride", where the crew would take somebody's car and fix it a lot.

Basically, you can read it like this:

>Maybe you can **fix** the manual

The following part doesn't make sense to me either though, and I'm a fluent English speaker:

>at that point you trapped to use cmake?

It's probable that what @lkwg82 is suggesting is that you could rewrite the provided manual at the point that it is worded incorrectly, and then make a pull request for the changes to the *manual*, not the cmake scripts.
