### ISSUE TITLE
CMake building on OS X is broken

### ISSUE THREAD

**Issue by stopiccot** [mozilla/mozjpeg#161]
I've installed nasm 2.11 from homebrew but still getting errors:

https://gist.github.com/stopiccot/ddeabc5160b6d5c71308

**Comment by pornel** [comment]
Libjpeg-turbo (which where it comes from) by design supports CMake **only** on Windows. All other platforms must use autotools.

**Comment by stopiccot** [comment]
I've created pull request that fixes this issue #162

**Comment by bdaehlie** [comment]
See discussion in PR #162
