### ISSUE TITLE
mozjpeg ends up in endless loop when used with I/O suspension

### ISSUE THREAD

**Issue by jlongman** [mozilla/mozjpeg#166]
I/O Suspension (see structure.txt, *§Suspendable processing* for more details) isn't properly handled:

(This code is based on v.3.0, but it goes back to v.1.0 and is not in turbojpeg v1.4.0 (I'm not familiar with both projects enough to know where what happened.))

`jcmaster.c:583`
```c
LOCAL(void)
copy_buffer (j_compress_ptr cinfo, int scan_idx)
{
  my_master_ptr master = (my_master_ptr) cinfo->master;
//... skip some
  while (size >= cinfo->dest->free_in_buffer)
  {
    MEMCOPY(cinfo->dest->next_output_byte, src, cinfo->dest->free_in_buffer);
    src += cinfo->dest->free_in_buffer;
    size -= cinfo->dest->free_in_buffer;
    cinfo->dest->next_output_byte += cinfo->dest->free_in_buffer;
    cinfo->dest->free_in_buffer = 0;
    (*cinfo->dest->empty_output_buffer)(cinfo);
  }
```

But `empty_output_buffer` isn't guaranteed to empty the buffer - rather it can return `FALSE` indicating an I/O suspension must occur, and the buffer must be emptied at a different level.  So this will loop endlessly, which is clearly undesirable.

This is called in this path:
```
#0  0x000000000043bf13 in copy_buffer (cinfo=0x8007073d8, scan_idx=0) at jcmaster.c:601
#1  0x000000000043c93c in select_scans (cinfo=0x8007073d8, next_scan_number=52) at jcmaster.c:745
#2  0x000000000043cdd9 in finish_pass_master (cinfo=0x8007073d8) at jcmaster.c:846
#3  0x0000000000438296 in jpeg_finish_compress (cinfo=0x8007073d8) at jcapimin.c:200
#4  0x00000000004132f5 in my_xcoder_jpeg_c::finish_crosscode (this=.........)
```
`my_xcoder_jpeg_c` is my company's proprietary code which uses I/O suspension. At this time I do not have scrubbed code which could be provided for the test - indeed my company would not likely approve such a release - but I'll make some effort to find open source software which uses I/O suspension.  The image which caused this discovery is available on the public internet but has a clause disallowing use and hyperlinking from other internet sites.  (Ugh).

Turned on `cinfo.err.trace_level` (=1): 
```
Start of Image
Miscellaneous marker 0xe1, length 22
Miscellaneous marker 0xec, length 15
Miscellaneous marker 0xe1, length 879
Adobe APP14 marker: version 100, flags 0xc000 0x0000, transform 1
Define Quantization Table 0  precision 0
Define Quantization Table 1  precision 0
Start Of Frame 0xc0: width=2000, height=1333, components=3
    Component 1: 2hx2v q=0
    Component 2: 1hx1v q=1
    Component 3: 1hx1v q=1
Define Huffman Table 0x00
Define Huffman Table 0x01
Define Huffman Table 0x10
Define Huffman Table 0x11
Start Of Scan: 3 components
    Component 1: dc=0 ac=0
    Component 2: dc=1 ac=1
    Component 3: dc=1 ac=1
  Ss=0, Se=63, Ah=0, Al=0
End Of Image
SCAN 0: 0 0 0 0
^Z
Program received signal SIGTSTP, Stopped (user).
0x000000000040bf02 in copy_buffer (cinfo=0x8007053d8, scan_idx=0) at jcmaster.c:606
606	    cinfo->dest->next_output_byte += cinfo->dest->free_in_buffer;
(gdb) print size
$1 = 3498
(gdb) print cinfo->dest->free_in_buffer
$2 = 0
(gdb)
```

**Comment by bdaehlie** [comment]
I believe we return an error now when I/O suspension is in use because we aren't going to be able to support it.
