### ISSUE TITLE
mozjpeg compiled with nasm 2.11.08 generates corrupt images

### ISSUE THREAD

**Issue by LostVector** [mozilla/mozjpeg#175]
I pulled from the head branch a few days ago and attempted to build and run mozjpeg on a Mac Pro with the following specs:

Mac Pro (Late 2013)
Processor: 3.5 GHz 6-Core Intel Xeon E5
Memory: 16GB RAM
OS X Yosemite: 10.10.3

cjpeg generated very corrupt images.  However, the same code built and run on my Macbook Pro Retina Mid 2014 worked fine.

It should be noted that I originally tried to run mozjpeg-3.0 release on the Mac Pro and it was crashing with a "DCT coefficient out of range" error.  Same code base, again, worked fine on my Macbook Pro.  So the error might go back quite a ways.

If configured with the --without-simd switch, cjpeg behaves correctly again on the Mac Pro.  Obviously, this would seem to point to some sort of optimization issue.

**Comment by pornel** [comment]
I've ran into the same issue. `make test` shows this immediately.

The problem affects all version of mozjpeg, even ones that used to work on OS X fine, so I think it's problem with tooling on OS X. Perhaps an incompatible version of nasm?

**Comment by LostVector** [comment]
I'm pretty sure I'm pointing to the homebrew version of nasm (the version of nasm built into OS X has never worked for me).  It's showing on the Mac Pro as

"NASM version 2.11.08 compiled on Mar 10 2015"

which hopefully is compatible?  My path has "/usr/local/bin" first as well.  I don't think mozjpeg even builds with the native version of nasm (which is good).

**Comment by pornel** [comment]
Yes, it's nasm 2.11.08 that's broken. nasm 2.11.06 compiles correctly.

**Comment by dgreensp** [comment]
Thank you for this, solved my problem!

**Comment by dcommander** [comment]
Verified that NASM 2.11.09 rc1 works properly.

**Comment by denji** [comment]
yasm too?

**Comment by dcommander** [comment]
YASM always worked.  This bug was specific to NASM.

**Comment by shinnn** [comment]
With NASM v2.12.01 I don't run into this issue.

**Comment by dcommander** [comment]
Yes, it was fixed in 2.11.09.

**Comment by LostVector** [comment]
Thanks, looks like this is fixed!
