### ISSUE TITLE
Image quality problem

### ISSUE THREAD

**Issue by mathi1993** [mozilla/mozjpeg#179]
Hey guys,

I have a problem with some images. I optimized them, but the result isn't that good...you can see it here:

Image 1 Original: http://futureweb.at/userdata/115/uploads/imagetests/image1_original.jpg
Image 1 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image1_optimized.jpg

Image 2 Original: http://futureweb.at/userdata/115/uploads/imagetests/image2_original.jpg
Image 2 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image2_optimized.jpg

Image 3 Original: http://futureweb.at/userdata/115/uploads/imagetests/image3_original.jpg
Image 3 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image3_optimized.jpg

Image 4 Original: http://futureweb.at/userdata/115/uploads/imagetests/image4_original.jpg
Image 4 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image4_optimized.jpg

Image 5 Original: http://futureweb.at/userdata/115/uploads/imagetests/image5_original.jpg
Image 5 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image5_optimized.jpg

Image 6 Original: http://futureweb.at/userdata/115/uploads/imagetests/image6_original.jpg
Image 6 Optimized: http://futureweb.at/userdata/115/uploads/imagetests/image6_optimized.jpg

As you can see above, it happens more often if the colors are very garish (Cyan, magenta, red,...).
Here is our optimize-call: /opt/mozjpeg/bin/cjpeg -progressive -optimize image.jpg  > image.jpg.out && mv image.jpg.out image.jpg
Our customers aren't happy with the quality of the images. Do you know if I can do anything about it?

Thanks and regards,
Mathias

**Comment by pornel** [comment]
Add `-sample 1x1` to preserve high-res color.

**Comment by futureweb** [comment]
Seems like we overlooked this parameter - Images looking way better now - thx for your help! ;-)

*can be closed*

**Comment by pornel** [comment]
Could be solved with #183
