### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/mozjpeg#185]
How we can install and use it?

**Comment by pornel** [comment]
If you want to compile it from scratch, then [instructions are in BUILDING.txt](https://github.com/mozilla/mozjpeg/blob/master/BUILDING.txt).

There are no official binaries. Some people have commented where you can get packages/binaries from: https://github.com/mozilla/mozjpeg/issues/91

For Mac there's `mozjpeg` in Homebrew and I've added mozjpeg to [ImageOptim](https://imageoptim.com/).

And if all else fails I've got [an online version](https://imageoptim.com/mozjpeg) that doesn't require any installation.
