### ISSUE TITLE
Is possible convert any image to JNG with mozjpeg optimizations?

### ISSUE THREAD

**Issue by ghost** [mozilla/mozjpeg#187]
Hello. I want to get JNG image with mozjpeg color and alpha channel streams. How to I can do it?

**Comment by pornel** [comment]
If you have a JNG converter that uses libjpeg it should "just work" if you replace libjpeg with mozjpeg implementation.

**Comment by acterhd** [comment]
It's have converter - named ImageMagick. But how to implement?
