### ISSUE TITLE
jpegtran options too limited

### ISSUE THREAD

**Issue by denlral** [mozilla/mozjpeg#188]
By default mozjpeg's jpegtran produces progressive files. They are smaller, but take substantially longer to decode, and there's no "-no-progressive" option that I can find.

It's possible to use -revert and then re-enable features, but it looks like you can't manually re-enable everything as "-revert -progressive -optimize" (-optimize actually does nothing when used along -progressive) still doesn't get you to the sizes you get with no parameters.

This makes me suspect that "-revert -optimize" isn't generating the smallest non-progressive file possible.

**Comment by sitsofe** [comment]
It's not clear from the but jpegtran  help but using ```-fastcrush``` might actually disable progressive - on the JPEGs I tried It made smaller file sizes than without...

**Comment by bdaehlie** [comment]
I'm not sure I totally understand the issue here, but in general we aren't interested in non-progressive. I don't recommend using mozjpeg as a replacement for general-purpose libraries like libjpeg-turbo.
