### ISSUE TITLE
Debian libjpeg replacement

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/mozjpeg#189]
Do you plan to release a Debian package that `Provides: libjpeg9` and `Conflicts: libjpeg8, libjpeg9, libjpeg62-turbo`? And ofcourse resides in `/usr/bin/`.

**Comment by CoolOppo** [comment]
You could use `checkinstall` to make it happen.

**Comment by bdaehlie** [comment]
We aren't planning to do anything distro-specific.
