### ISSUE TITLE
npm install of mozjpeg@4.0.1 horribly slow

### ISSUE THREAD

**Issue by ajayindfw** [mozilla/mozjpeg#194]
As part of our iOS and Android builds for a hybrid mobile application built using JS, HTML5 and CSS, we are using npm install to install our dependencies.  One of the dependency "ionic-minify" through a series of dependencies and transitive dependencies calls "mozjpeg@4.0.1 install which then calls:

mozjpeg@4.0.1 postinstall <root-folder>/<app-folder-name>/node_modules/mozjpeg 
node lib/install.js

This step takes forever (almost 30-40 minutes) to finish on a Mac Mini where we are running a ci server to automatically build iOS and Android mobile packages.  I have tried increasing the verbose level of npm log in an attempt to find the source of the problem but unfortunately the logging verbosity level only applies to the direct dependencies specified in my application packages.json and does not provide verbose logging information when the first level dependencies do "npm install" on their dependencies as part of the build of our application.

Please help.

**Comment by pornel** [comment]
My guess is that it's compiling the library from source, but even then it should be few minutes at most. Maybe it's not running make with `-j4` argument that allows parallel compilation?

However, this project only maintains a C version of the library. The node version is maintained by others: https://github.com/imagemin/mozjpeg-bin - you should file a bug there.
