### ISSUE TITLE
not satisfying results

### ISSUE THREAD

**Issue by danielhq** [mozilla/mozjpeg#196]
Hello everyone
I took a random image from the internet (approx. 14 MB)  and run it with 
mozjpeg -optimize -copy none -outfile file-opt.jpg file.jpg
Which results in a 13 MB file.
This test is made on  centOS server, with mozjpeg 3.0 

I ran the same test on my machine(os x) with the same image and the result is approx. 3.7 MB
I don't know what I am missing.

**Comment by pornel** [comment]
14 > 13MB change is typical for lossless operation. 14 > 3.5MB likely involved reduction of quality. Perhaps you've used jpegtran in the first case and cjpeg in the second?

**Comment by danielhq** [comment]
@pornel Thats what i was thinking, how can i know and switch between the two?

**Comment by pornel** [comment]
I've described some features used by the webtool here: http://calendar.perfplanet.com/2014/mozjpeg-3-0/

**Comment by danielhq** [comment]
Yes, I've read the post :) and I accomplished the same results on my machine, but I wanted the same results on my server, since i thousands images i can't download them all and re-upload them.

Is there a way to switch between jpegtran and cjpeg?

**Comment by pornel** [comment]
These are two separate commands. I don't know where you're getting "mozjpeg" command from.

**Comment by danielhq** [comment]
Oops I forgot it was a simple symlink to jpegtran, my bad :D
Thats why i was feeling lost.
