### ISSUE TITLE
more Multiple Scan / progressive docs/examples?

### ISSUE THREAD

**Issue by tomByrer** [mozilla/mozjpeg#197]
I'd like to experiment with various settings for progressive encoding.  Namely, I'd like more control on how obtuse the first scan or two are.  The [current docs for the the `-scan`](https://github.com/mozilla/mozjpeg/blob/master/wizard.txt#L113) parameter are hard for me to fully understand.  Are there other config examples or blog posts I can read please?

**Comment by pornel** [comment]
I've found this to be useful:

http://hodapple.com/blag/2011/11/24/obscure-features-of-jpeg.html

Note that the very first scan has to be DC only, so the ugliest blockyness is unavoidable.

I wish decoders were smarter about it and applied blur proportional to amount of data available:

https://imageoptim.com/progressiveblurdemo.html
