### ISSUE TITLE
cjpeg does not accept .jpg files as input

### ISSUE THREAD

**Issue by matyasatfp** [mozilla/mozjpeg#200]
I'm trying your tool on Windows.

If I execute "cjpeg -quality 80 input.jpg > out.jpg" I get an error:   
Unrecognized input file format --- perhaps you need -targa    

Due to https://github.com/mozilla/mozjpeg/issues/144 in Windows .png is not supported, is .jpg as an input not supported on Windows either?

I am using the 3.1 binary from http://mozjpeg.codelove.de/binaries.html

**Comment by pornel** [comment]
Maybe you have an old non-MozJPEG version in `$PATH`. What do you get when you run `cjpeg -h` or `cjpeg -v`?

**Comment by matyasatfp** [comment]
Sorry, it turned out I was testing with a corrupted jpg image.
