### ISSUE TITLE
Buffer size regression test very slow

### ISSUE THREAD

**Issue by felixbuenemann** [mozilla/mozjpeg#201]
The "Buffer size regression test" run by `tjunittest` is insanely slow compared to the same test in `libjpeg-turbo` making running `make test` as part of a packaging workflow unfeasible.

For comparison on libjpeg-turbo master `make tjquicktest` finishes in under 30 seconds, while on mozjpeg I'm already running for 25 minutes and it only progressed to the second of six subsampling tests in the first colorspace.

**Comment by felixbuenemann** [comment]
Btw. the first run of `./tjunittest` without arguments took about 8 hours on a pretty recent Core i7 3.1 GHz 13" MacBook Pro. I also started the test on a linux box, which is currently at ~14h cpu time.

**Comment by felixbuenemann** [comment]
The test finished with ~15 hours cpu time.

**Comment by pornel** [comment]
I believe this is caused by a memory leak in mozjpeg. 99% of the time is spent in `alloc_small` searching through linked list of objects.

The memory pool with id = 0 keeps accumulating objects and quickly reaches hundreds of thousands (while other pools have 0 or 1 objects). In libjpeg-turbo the pool also has max 1 object.

**Comment by pornel** [comment]
It's caused by

```c
master->saved_dest = cinfo->dest;
cinfo->dest = NULL;
…
jpeg_mem_dest(cinfo, …
```

which leaks.

**Comment by felixbuenemann** [comment]
@pornel Are you sure this is fixed? I checked out your temppool branch and `make test` still takes forever, while `TJ_REVERT=1 make test` finishes in 26 seconds.

**Comment by pornel** [comment]
It changes it from long-forever to short-forever. I think the remaining difference is just due to progressive + trellis being so much slower than the default compression.

**Comment by felixbuenemann** [comment]
😄 Yeah, seems I wasn't patient enough. It now finishes in 420 seconds on my machine.
