### ISSUE TITLE
mozjpeg zero-byting files

### ISSUE THREAD

**Issue by lubomski** [mozilla/mozjpeg#204]
Apologies for double posting this (posted this to https://github.com/imagemin/imagemin-mozjpeg/issues/9 but was closed); but i'm really struggling to get to the root cause of this issue.

Seem to be experiencing an earlier reported issue with mozjpeg zero-byting files... using grunt-contrib-imagemin 1.0.0 and imagemin-mozjpeg 5.1.0

When installing I get the error /node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly. Compiling from source reports it builds successfully.

Have swapped to jpegoptim in gruntfile and works as intended, however compression is nowhere as good as mozjpeg.

OSX 10.11.4 (Mac Pro)
Node 5.10.0
npm 3.8.3
NASM version 2.12.01 compiled on Mar 23 2016

Ran same sample project on a vanilla Win 10 virtual machine; installed node & Grunt; mozjpeg worked out of the box...

Does anyone have any suggestions as to where to look at next? I'm guessing this is an architecture issue  given it works directly in the Windows environment, or my setup is borked somehow)

**Comment by pornel** [comment]
Sorry, this project doesn't maintain the mozjpeg node module. If compiling binary from source solves the problem, then you need to find who compiled the node module you're having problem with.

**Comment by lubomski** [comment]
apologies; closing issue

**Comment by lubomski** [comment]
@pornel after a rather abrupt and rude lock of the thread on the imagemin-mozjpeg project; it seems that shinnn was pointing the finger at the main binary...

I've done some quick testing and seems setting the version in the package.json to 5.0.0 or less makes it work; setting it to latest 5.1.0 breaks. I assume that the imagemin-mozjpeg is pulling the core mozjpeg in...

I'm really not adept enough to say one way or the other where the issue lies; i've done my best to report the issue in what I believe is the right areas...
