### ISSUE TITLE
.deb file generated doesn't work properly

### ISSUE THREAD

**Issue by freedom1989** [mozilla/mozjpeg#209]
Hi all,
my environment is:    
**OS**:
    Linux 3.16.0-4-amd64 #2 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-03-10) x86_64 GNU/Linux
**mozjpeg**:
    mozjpeg-3.1-release-source.tar.gz

I make a deb package following the BUILDING.txt:
```bash
tar -xf mozjpeg-3.1-release-source.tar.gz
cd mozjpeg
./configure
make
make deb
```

then I test the generated `cjpeg` by:
```bash
./cjpeg -quality 85 ~/input.jpeg
```
it works!

then I publish the generated .deb file to my private repository. and run the following command to install the package in the same machine:
```bash
apt-get update
apt-get install mozjpeg
```
the I run the same test:
```bash
cjpeg -quality 85 ~/input.jpeg
```
I got the following error:
```bash
cjpeg: relocation error: cjpeg: symbol jpeg_float_quality_scaling, version LIBJPEG_6.2 not defined in file libjpeg.so.62 with link time reference
```

any idea?

**Comment by pornel** [comment]
Looks like you're running mozjpeg's new cjpeg with system's old libjpeg.

**Comment by freedom1989** [comment]
@pornel seems you're right. do you know how to publish the `.deb` package correctly(with the correct vertions of libjpeg)?

**Comment by pornel** [comment]
No, sorry.

I use `./configure --disable-shared --enable-static` and get a standalone `cjpeg` that doesn't need any dependencies.

**Comment by freedom1989** [comment]
@pornel thanks, this works for me.
