### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/mozjpeg#214]
Do you plan to release a new version for these 2201 commits?
https://github.com/mozilla/mozjpeg/releases

**Comment by pornel** [comment]
Yes #208

**Comment by szepeviktor** [comment]
Thank you.
So the only thing in this milestone is #181

**Comment by abarre** [comment]
@pornel, do you have any plan in releasing 3.2 in the next weeks or months since libjpeg-turbo 1.5.0 has been merged in the master ?

**Comment by pornel** [comment]
I've packaged current master as v3.2. Please test it.

**Comment by abarre** [comment]
Sure, thank you very much.
I will test it this week and let you know.

**Comment by szepeviktor** [comment]
It looks OK: https://travis-ci.org/danielgtaylor/jpeg-archive/jobs/201744487#L170
