### ISSUE TITLE
Compatability Replace libturbojpeg library with mozjpeg generated library

### ISSUE THREAD

**Issue by Anaiappan** [mozilla/mozjpeg#219]
Hi, 
Can i replace any version of LibTurboJpeg library with any version(V2.1, V3.0 or V3.1) of MozJpeg generated libraries ? or are there any compatibility that we need to follow?

**Comment by pornel** [comment]
Don't use mozjpeg 2.x or older.

mozjpeg 3.0/3.1 is compatible with libjpeg-turbo 1.4 and the version in master is libjpeg-turbo 1.5. 

Generally they all are binary compatible. The only gotcha (same as in libjpeg-turbo) is knowing what version of libjpeg ABI you need (6b, 7, 8) - that depends on your system/distribution.

**Comment by Anaiappan** [comment]
Thanks :)
