### ISSUE TITLE
Encoding failure when using many scans (>60)

### ISSUE THREAD

**Issue by MegaByte** [mozilla/mozjpeg#220]
When using many scans, the jpegtran fails with "Bogus virtual array access"
This failure occurs with more than 60 scans even though https://github.com/mozilla/mozjpeg/blob/a53303b82e56cdbe38a0cd90fe6124fd62a77353/rdswitch.c#L193 suggests 100 scans should work. In any case, IJG jpegtran does not fail even with hundreds of scans.

**Comment by ValZapod** [comment]
Fixed in https://github.com/mozilla/mozjpeg/commit/c743009717878cb22a5434c798dae5d3879d6ca2 then.

**Comment by MegaByte** [comment]
This seems to have been closed accidentally as the commit is unrelated. Anyway, I think this behavior is related to the hard-coded arrays of size 64 in https://github.com/mozilla/mozjpeg/blob/fd569212597dcc249752bd38ea58a4e2072da24f/jcmaster.h#L35-L37

**Comment by MegaByte** [comment]
@kornelski please reopen?
