### ISSUE TITLE
Non-progressive scan configurations ignored

### ISSUE THREAD

**Issue by MegaByte** [mozilla/mozjpeg#221]
Sequential scans requested through jpegtran are ignored and progressive files are produced. For example, the scan sequence below does not generate a file with the requested scans.

0;
1;
2;

**Comment by pornel** [comment]
Is this mozjpeg-specific? Does libjpeg-turbo generate files as you expect?

**Comment by MegaByte** [comment]
Yes, this only affects mozjpeg. libjpeg-turbo works as expected.
