### ISSUE TITLE
version `LIBJPEGTURBO_6.2' not found (required by ./cjpeg)

### ISSUE THREAD

**Issue by mkrishtopa** [mozilla/mozjpeg#227]
ubuntu 14
mozjpeg 3.0 release tar.gz

> sudo apt-get install libjpeg-turbo8 libjpeg8 libjpeg8-dev
> ./configure
> make
> cd .libs
> ./cjpeg
> 

./cjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so.62: version `LIBJPEGTURBO_6.2' not found (required by ./cjpeg)

**Comment by pornel** [comment]
You can't run anything from `.libs` directly. Either run `./cjpeg` from root directory, which is a shell script that will fake an installation on the fly, or run `make install` and run the installed command.

**Comment by mkrishtopa** [comment]
Thanks, @pornel 

Don't like all this installation headache, so I just installed mozjpeg from https://www.npmjs.com/package/mozjpeg :-) Easy way.

**Comment by HansMeiser234** [comment]
Hello,

have the same issue on Ubuntu16:

ldd cjpeg
./cjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so.62: version `LIBJPEGTURBO_6.2' not found (required by ./cjpeg)
        linux-vdso.so.1 =>  (0x00007ffe3c3f0000)
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007fd4f827b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd4f7eb1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd4f84a0000)

Reason is that /usr/lib/x86_64-linux-gnu/libjpeg.so.62 belongs to ubuntu-package libjpeg62 an this lib is used first but has wrong symbols.  After removing libjpeg62 it looks a different way:

(ldd tests should work in quite all subfolders)
ldd cjpeg  
        linux-vdso.so.1 =>  (0x00007ffde9dfe000)
        libjpeg.so.62 => /usr/lib/libjpeg.so.62 (0x00007f99c8076000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f99c7cac000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f99c79a3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f99c8312000)

Now binary is bind to /usr/lib/libjpeg.so.62 which belongs to mozjpeg installation and not the system-lib.
Basic Problem is, that mozjpeg filesnames  collide with filesnames of Systemlibs. This systemlibs should be removed too, but may be package deinstallation requires deinstallation of some more useful packages. In my case deinstallation of libjpeg62 requires also deinstallation of depending libgs8,libtiff4

Hans

**Comment by pornel** [comment]
If you have other copy of libjpeg on the system, you have two options:

* uninstall it
* or `./configure` mozjpeg with `--prefix` that points to a private non-system directory

**Comment by HansMeiser234** [comment]
Hello,
thanks for your answer.
In my case it was best to remove not needed package libjpeg62.  Changing --prefix to non-standard-folders is a problem for us. In Hosting we use apparrmor to restrict execution of binaries to typical folders for security reasons.  In this case we had to extend allowed paths, what we want to avoid.
May be the Topicopener reads this and understand the problem from months ago.  So iam happy with this.

Hans
