### ISSUE TITLE
Using `jpegtran` and `mozjpeg` together give some confusing

### ISSUE THREAD

**Issue by evilebottnawi** [mozilla/mozjpeg#229]
If you use the first `jpegtran` and then `mozjpeg`, the file size becomes much smaller than the use only `mozjpeg`. This is normal behavior? Or `jpegtran` have some algorithms are better than `mozjpeg`?

`mozjpeg` options - `progressive`, `quality` - `80`.
`jpegtran` options - `progressive`.

**Comment by pornel** [comment]
There is no `mozjpeg` command. This project ships `cjpeg` and `jpegtran`. Are you using a 3rd party tool that wraps them or renames them?

The differences is that `cjpeg` changes quality, and `jpegtran` doesn't, so they're very different.

I think `cjpeg` copies over embedded color profiles, so if you use `jpegtran` to strip profiles (either before or after), the file will be smaller.

**Comment by evilebottnawi** [comment]
@pornel thanks for answer, i am use `imagemin-mozjpeg` (he use https://github.com/imagemin/mozjpeg-bin  - inside package using `cjpeg` bin) package on `nodejs`. Is it possible to create the same behavior as `jpegtran` using `mozjpeg`?

**Comment by evilebottnawi** [comment]
@pornel  It is interesting that if you use `jpegtran` before `mozjpeg` - file done smaller than use converselyю

**Comment by pornel** [comment]
`jpegtran` before `cjpeg` is not a valid result. It does not make compression any more efficient. Any difference is accidental, e.g. due to loss of color profiles.

**Comment by evilebottnawi** [comment]
@pornel thanks for clarification :smile:

**Comment by pornel** [comment]
Sorry, I've deleted my previous comment, because I wasn't sure about it. 

In general I'd recommend `cjpeg` first, and then `jpegtran`, since that's the most logical — lossy compression followed by lossless improvement.

Since `cjpeg` doesn't support color profiles, the result could be the same regardless of order they're used, but I'm surprised that running `jpegtran` first improves things. It may be a bug or some weird metadata that changes how image appears to cjpeg.

**Comment by evilebottnawi** [comment]
@pornel 
`cjpeg` -> `jpegtran` - good (good quality and good filesize)
`jpegtran` -> `cjpeg` - bad (bad quality and bad filesize)
Am i right ? :smile:

**Comment by pornel** [comment]
yes

**Comment by CoolOppo** [comment]
> In general I'd recommend cjpeg first, and then jpegtran, since that's the most logical order: lossy compression followed by lossless improvement.

Wait a minute... `jpegtran` can further optimize a file encoded using mozjpeg's `cjpeg`?!

**Comment by pornel** [comment]
Well, depends. cjpeg makes progressive by default. For small images if you add `-baseline` it might be a bit smaller.
