### ISSUE TITLE
add -copy none to cjpeg

### ISSUE THREAD

**Issue by androidland** [mozilla/mozjpeg#230]
please add option to strip exif info for cjpeg

**Comment by CoolOppo** [comment]
use jpegtran

**Comment by saurabheights** [comment]
IMHO, I'm not sure if this should get a thumb down. MozJpeg project itself states its goal to "reduce the size of JPEG files without reducing quality". An option to remove metadata which can reduce the file size could lead to significant size reduction.

Integration of jpegtran to mozjpeg can be the easiest solution and definitely simpler for users as well.

**Comment by pornel** [comment]
Indeed, `jpegtran` is the right way to do this.
