### ISSUE TITLE
jpegtran: Add option to overwrite the input file, if size is smaller

### ISSUE THREAD

**Issue by dmak** [mozilla/mozjpeg#231]
Would be nice if `jpegtran` could overwrite input file preserving it's modification timestamp in case if transformation step had resulted a smaller file (e.g. subsequent invocations of `jpegtran` with same arguments should not modify file as it would obviously be the same).

**Comment by pornel** [comment]
That would be useful in non-mozjpeg jpegtran too, so you should ask libjpeg-turbo to add it. MozJPEG is based on libjpeg-turbo and we try to keep differences minimal.

**Comment by dmak** [comment]
Closing as upstream feature request is rejected.
