### ISSUE TITLE
Mozjpeg produce images with different size on mac and windows

### ISSUE THREAD

**Issue by shrpne** [mozilla/mozjpeg#233]
This leads to situation, when each commit to git write all changed images, so repository grows very fast.

Not all images have different size, but about 90% of jpeg's

I build images with gulp-imagemin. Option provided to mozjpeg is `{quality: 90}`
Modules used on mac and windows installed with npm-shrinkwrap.json:
gulp-imagemin@3.1.1
imagemin@5.2.2
imagemin-mozjpeg@6.0.0
mozjpeg@4.1.1

There are a lot of images, so gitignore them and manual copying is not very handy.
Not sure if it can be fixed and what the cause of the problem.

**Comment by pornel** [comment]
Those are tools provided by others, and we don't support them. You should file bugs with them first.

The difference may come from different options or different versions built for each OS.

Also, every time you recompress JPEG you lose quality (you get 90% of 90% of 90%, etc. which is less than 90% quality), so it's normal that file size changes. Optimize ones and don't touch them again.

**Comment by shrpne** [comment]
@pornel thank you for reply.
Those npm modules are just wrappers, so I thought they should not affect compression result.
But I file an issues to imagemin too.

I store two versions of images: source and minified. And always minify from source.

npm module mozjpeg@4.1.1 install this version: https://github.com/mozilla/mozjpeg/archive/v3.1.tar.gz
So usually mozjpeg on mac and windows should generate equal files and there are no OS specific algorithms? Is it possible to check what options are set on installed mozjpeg?

**Comment by pornel** [comment]
There shouldn't be a difference if the same version with the same build and run-time configuration is used on the same CPU architecture.

However, I know nothing about the Node modules - how they're built, how they're configured. Please report this to maintainers of the Node packages and have them report precisely problems they find, specifically in the C library.
