### ISSUE TITLE
Consider also providing a GIMP plugin to replace the built-in JPEG exporter

### ISSUE THREAD

**Issue by hfhchan** [mozilla/mozjpeg#235]
The current GIMP output plugin generates rather inefficient output as it uses vanilla libjpeg.  Providing compiled binaries for both Windows/Linux would be much more convenient workflow for designers/developers than having to first save as PNG then outputting a JPEG via command line.

**Comment by pornel** [comment]
This project provides drop-in replacement for libjpeg for other developers to use, but does not intend to develop tools and plugins for all software.

Please ask GIMP to use mozjpeg instead of libjpeg.
