### ISSUE TITLE
Gruetzli support

### ISSUE THREAD

**Issue by staabm** [mozilla/mozjpeg#242]
Will mozjpeg also make use of https://github.com/google/guetzli in cases where it could provide filesize reductions?

**Comment by pornel** [comment]
You can use MozJPEG's `jpegtran` to losslessly compress files from Guetzli even further.

However, I don't think it makes sense to include Guetzli as-is in MozJPEG currently:

* Guetzli is seriously slow. In my quick test it took 10 seconds to produce a 38KB file, which was **120 times slower than MozJPEG**.
  Guetzli is a very young project, so it's likely that it will get much faster, but currently its speed makes it unsuitable for many use-cases that MozJPEG can do (recompression on the fly, very high-resolution digital camera images, etc.)

* Guetzli only supports highest quality settings (close to `-quality 90` setting in JPEG), which is fine if you want nearly perfect images, but MozJPEG aims to support wide range of qualities. If you want smallest file size and you only need "good enough" quality, you'll get smaller files from MozJPEG (Guetzli's "bees" example is 38KB and looks great, but MozJPEG compresses it down to 16KB at cost of some distortions).

It probably makes more sense for Guetzli to include MozJPEG's lossless compression instead :)

**Comment by saurabheights** [comment]
Expanding to pornel's response, Guetzli demands high memory, few GB's for large images. The image in this [issue](https://github.com/google/guetzli/issues/11#issuecomment-272153260) is around 24 MP(4Kx6K) and ends up using 5GB mem which makes it highly impractical.
