### ISSUE TITLE
ubuntu 16.10 mozjpeg pre-build test failed

### ISSUE THREAD

**Issue by trixan** [mozilla/mozjpeg#244]
ubuntu 16.10
npm install:

mozjpeg@4.1.1 postinstall /node_modules/mozjpeg
node lib/install.js

  ⚠ The `node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/node_modules/mozjpeg/vendor" --bindir="/node_modules/mozjpeg/vendor" --libdir="/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: ./configure --disable-shared --prefix="/node_modules/mozjpeg/vendor" --bindir="/node_modules/mozjpeg/vendor" --libdir="/node_modules/mozjpeg/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by pornel** [comment]
The message says you don't have `nasm` installed. Install `nasm`.

**Comment by trixan** [comment]
Resolved thanks!

**Comment by Fredkiss3** [comment]
> 
> 
> The message says you don't have `nasm` installed. Install `nasm`.

How do i install `nasm` ?

**Comment by kornelski** [comment]
It depends on your platform. If you're on Linux, there's probably `nasm` package for the package-manager of your distro. See also https://www.nasm.us

**Comment by yongyiwong** [comment]
when I install mozjpeg globally and mozjepg --help, I got this error.
Environment:  Ubuntu 22.04.1 LTS
Node version: 14.20.0

Here is the command I tried.

```
npm -g install mozjpeg
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/home/gf/.nvm/versions/node/v14.20.0/bin/mozjpeg -> /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/cli.js

> mozjpeg@8.0.0 postinstall /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg
> node lib/install.js

+ mozjpeg@8.0.0
added 163 packages from 52 contributors in 49.827s
```

```
mozjpeg --help

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
  path: '/home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
  spawnargs: [ '--help' ]
}

```

Actually when post install, I don't get any error or message.
Also I have installed all packages automake autoconf libtool dpkg pkgconfig nasm libpng

Is there anyone faced this issue?

Thanks.
