### ISSUE TITLE
Unable to build cjpeg as static library

### ISSUE THREAD

**Issue by ostatnicky** [mozilla/mozjpeg#245]
Can you give me an advice how to build `cjpeg` binary for macOS which would be static library?

I'm running everything like does https://github.com/imagemin/mozjpeg-bin/blob/master/lib/install.js
but final binary has only 47kb. I expect size around ~500kb.

My  problem is that I'm missing `libpng16.16.dylib` when I'm running `cjpeg`.

```
./cjpeg test.jpg > result.jpg 
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/xxx/test/./cjpeg
  Reason: image not found
Abort trap: 6
```

**Comment by pornel** [comment]
On macOs you'd need:

```sh
./configure libpng_LIBS='/usr/local/lib/libpng16.a -lz' --enable-static --disable-shared
make
```

In case of link errors substitute `/usr/local/lib/libpng16.a` for whatever `find /usr -name libpng*.a` finds.

On other platforms you may need to replace `-lz` with a path to a static `libz.a`.

**Comment by ostatnicky** [comment]
Thank you very much! I works! :)
