### ISSUE TITLE
Problems building mozjpeg on centos 6

### ISSUE THREAD

**Issue by lexbi** [mozilla/mozjpeg#247]
Hi,

I'm having trouble building the latest mozjpeg on Centos 6. 

I've been looking at this guide: https://blarg.co.uk/blog/how-to-install-mozjpeg

I have yum installed libtool, autoconf, automake, nasm & make.

I cd into the mozjpeg then run `autoreconf -fiv` though I appear to get an error where a lot of threads suggest libtool is not installed, but running `yum install libtool` returns `Package libtool-2.2.6-15.5.el6.x86_64 already installed and latest version Nothing to do`

The errors I initially get are as follows:

    autoreconf -fiv
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
    libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
    libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
    autoreconf: running: /usr/bin/autoconf --force
    configure.ac:236: error: possibly undefined macro: m4_argn
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

If I add `AC_CONFIG_MACRO_DIR([m4])` to configure.ac I get the following:

    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
    autoreconf: running: /usr/bin/autoconf --force
    configure.ac:236: error: possibly undefined macro: m4_argn
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

If I add `ACLOCAL_AMFLAGS = -I m4` to Makefile.am

    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    autoreconf: running: /usr/bin/autoconf --force
    configure.ac:236: error: possibly undefined macro: m4_argn
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

Does anyone have any suggestions on this?

**Comment by pornel** [comment]
Use the official release and you won't need to mess with `autoreconf`:

https://github.com/mozilla/mozjpeg/releases

**Comment by lexbi** [comment]
Ah many thanks, I'll give that a go, I was just grabbing the latest with`git clone https://github.com/mozilla/mozjpeg.git`

**Comment by lexbi** [comment]
got the tar file and got it installed now thanks! I guess when I last cloned the master branch was possibly 3.1,

Cheers dude.
