### ISSUE TITLE
Same output and input

### ISSUE THREAD

**Issue by wgrrobin** [mozilla/mozjpeg#248]
Is it possible to have the same output and input in mozjpeg?

In jpegtran I can do: "jpegtran -outfile input.jpg input.jpg"
But when I do: "cjpeg -outfile input.jpg input.jpg"
I get this error message: "string(16) "Empty input file".

**Comment by pornel** [comment]
No, it doesn't support that. 

For `jpegtran` it makes sense, since it can operate losslessly. But `cjpeg` is a lossy tool, and you're overwriting your original file with a lossy derivative of it. And if you accidentally run that multiple times, you'll cause unnecessary generation loss in JPEG.

So it's best if you treat `cjpeg` as an "export" tool, rather than in-place optimization tool.

**Comment by wgrrobin** [comment]
Good point, that makes sense.
Thank you! :)

**Comment by alexander-schranz** [comment]
Hello,

I hang into this issue and hope we can reopen it.

@kornelski I know your point but there are other usecases where you don't want to copy your current file. In my case I download a original file -> run some optimizers -> upload the optimized file. In this case I don't want to create multiple files.

**Comment by kornelski** [comment]
That's true. It's a painful problem that applications are not using MozJPEG as built-in C library. The original vision for this project is that you *wouldn't even know it exists*, and it would be built into ImageMagick, GIMP, and perhaps even Photoshop and other programs that produce JPEG images.

The `cjpeg` command is a 20-year-old *demo* program that nobody cared about until MozJPEG, and nobody wants to touch. It wasn't supposed to be used for anything serious by anyone.

So if you're building a product around MozJPEG, please stay away from `cjpeg` as far as you can.

**Comment by alexander-schranz** [comment]
@kornelski thank you for your fast response. Sorry for my inexperience what is the best way to reduce the filesize using the jpegtran command from mozJpeg project?

**Comment by 2ji3150** [comment]
I can't use jpegtran for same input file. 
Does the behavior changed?

> jpegtran-static.exe test.jpg > test.jpg

`Empty input file`

> jpegtran-static.exe -outfile test.jpg test.jpg

`can't open test.jpg for reading`

**Comment by kornelski** [comment]
When you redirect stdout, the shell replaces the file before launching the command. It's impossible to support that.
