### ISSUE TITLE
Compiler errors when building on Windows (Visual C++)

### ISSUE THREAD

**Issue by JosePineiro** [mozilla/mozjpeg#250]
I have:
- Windows 7 x64
- Visual studio 2013
- cmake 3.8.0

I make:
- open the visual studio commandline ("Símbolo del sistema de las herramientas nativas de VS2013 x64" shorcut)
- vcvars64.bat  (set the enviroment variables)
- cd\mozjpeg-3.2-pre  (go to sources directory)
- cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .
- nmake

And get this error: 
[ 56%] Linking C executable cjpeg-static.exe
cjpeg.c.obj : error LNK2019: símbolo externo jinit_read_jpeg sin resolver al que se hace referencia en la función select_file_type
cjpeg-static.exe : fatal error LNK1120: 1 externos sin resolver
LINK failed. with 1120
(unresolver extern simbol jinit_read_jpeg refered in function select_file_type)

The version 3.1 compiled ok. No error in the same PC with the same commads

**Comment by pornel** [comment]
`rdjpeg.c` is missing from the build.

**Comment by pornel** [comment]
I don't know why though. It seems to be included in cmake:

```
if(ENABLE_STATIC)
  add_executable(cjpeg-static cjpeg.c cdjpeg.c rdgif.c rdppm.c rdjpeg.c rdswitch.c
    ${CJPEG_BMP_SOURCES})
```

**Comment by JosePineiro** [comment]
This bug are fix in the last versions.
