### ISSUE TITLE
compress so slow

### ISSUE THREAD

**Issue by liungkejin** [mozilla/mozjpeg#256]
I build mozjpeg for android, but compress bitmap to jpeg so slow! 
`(Bitmap 1080 x 1920, quality 100, compress need 3s) on OnePlus 3`

My build configuration
```
NDK_PATH="${ANDROID_NDK_PATH}"
BUILD_PLATFORM="darwin-x86_64"
TOOLCHAIN_VERSION="4.9"
ANDROID_VERSION="19";

# 32-bit ARMv7 build
HOST=arm-linux-androideabi
SYSROOT=${NDK_PATH}/platforms/android-${ANDROID_VERSION}/arch-arm
ANDROID_CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon -fprefetch-loop-arrays \
  --sysroot=${SYSROOT}"
```

My code
```
tjhandle handle = tjInitCompress();
int result = tjCompress2(handle,
                             argb, width, width*tjPixelSize[TJPF_RGBA], height, TJPF_RGBA,
                             &jpeg, &jpegSize, TJSAMP_444, quality, 0);
```

**Comment by pornel** [comment]
It's normal that encoding with MozJPEG is a few times slower than with plain libjpeg-turbo.

BTW, quality 100 is inappropriate for JPEG. The file is going to be a few times larger (and therefore also compress slower) than more usual quality in range 70-90.
