### ISSUE TITLE
turbojpeg uses different defaults

### ISSUE THREAD

**Issue by zivillian** [mozilla/mozjpeg#260]
The defaults for jpegtran introduced by 1d3533f are not applied to the turbojpeg library.

#### Disclaimer
I've attached a patch, which tries to mimic the behaviour of jpegtran in tjTransform, but I never learned c - so please be lenient.

I found this issue while trying to convert testimgint.jpg to grayscale using the turbojpeg API from a [c# wrapper](https://github.com/ahdde/ahd.mozjpeg/blob/aacc0b84790d00e064a1aac276c03f501e539571/TurboJpegWrapper.Tests/TJTransformerTests.cs#L31).

#### Description
Without this patch, the test failes with an AccessViolationException because `cinfo->num_scans` is set to 64 instead of 23 so `cinfo->master->is_last_pass` in `jpeg_finish_compress` is still 0 after 45 "passes".
This results in setting `cinfo->cur_comp_info` to uninitialized values (uninitialized component_index) which is used to access `coef->whole_image` in `compress_output`.

I've only tested this on Windows (x86 and x64).
#### Patch
```
diff --git "a/turbojpeg.c" "b/turbojpeg.c"
index 0b9718b..c37f7f2 100644
--- "a/turbojpeg.c"
+++ "b/turbojpeg.c"
@@ -2090,6 +2090,10 @@ DLLEXPORT int DLLCALL tjTransform(tjhandle handle,
 			&xinfo[i]);
 		if(!(t[i].options&TJXOPT_NOOUTPUT))
 		{
+#ifdef C_PROGRESSIVE_SUPPORTED
+			if (cinfo->num_scans != 0)     /* process -progressive; -scans can override */
+				jpeg_simple_progression(cinfo);
+#endif
 			jpeg_write_coefficients(cinfo, dstcoefs);
 			jcopy_markers_execute(dinfo, cinfo, JCOPYOPT_ALL);
 		}
```

**Comment by pornel** [comment]
Thank you. That makes sense. The Turbo API unfortunately doesn't get proper maintenance in this project.
