### ISSUE TITLE
Errors while build rpm package (CentOS 7.4.1708 x86_64)

### ISSUE THREAD

**Issue by zevilz** [mozilla/mozjpeg#272]
```
Processing files: mozjpeg-3.3.1-20171121.x86_64
error: File not found: /tmp/mozjpeg-build.OeYEGd/BUILDROOT/mozjpeg-3.3.1-20171121.x86_64/opt/mozjpeg/doc

RPM build errors:
    line 38: prereq is deprecated: Prereq: /sbin/ldconfig
    File not found: /tmp/mozjpeg-build.OeYEGd/BUILDROOT/mozjpeg-3.3.1-20171121.x86_64/opt/mozjpeg/doc
```

**Comment by pornel** [comment]
Unfortunately I can't help. Please report it to author of the RPM.

**Comment by jopaha** [comment]
Hello @zevilz,
did you find a sultion on that make rpm issue?

**Comment by zevilz** [comment]
Hello @jopaha, no.

**Comment by jopaha** [comment]
Hello @zevilz,
I`ve managed to build the RPM with the following SPECfile:

# Path under which mozjpeg should be installed
%define _prefix /usr/bin/mozjpeg

# Path under which executables should be installed
%define _bindir /usr/bin/mozjpeg/bin/

# Path under which Java classes and man pages should be installed
%define _datadir /usr/bin/mozjpeg/share

# Path under which docs should be installed
%define _docdir /usr/share/doc/%{name}-%{version}

# Path under which headers should be installed
%define _includedir /usr/bin/mozjpeg/include

%if "%{?__isa_bits:1}" == "1"
%define _bits %{__isa_bits}
%else
# RPM < 4.6
%if "%{_lib}" == "lib64"
%define _bits 64
%else
%define _bits 32
%endif
%endif

%if "%{_bits}" == "64"
%define _libdir %{_exec_prefix}/lib64
%else
%if "%{_prefix}" == "/usr/bin/mozjpeg"
%define _libdir %{_exec_prefix}/lib32
%endif
%endif

# Path under which man pages should be installed
%define _mandir /usr/bin/mozjpeg/share/man

Summary: A JPEG codec that provides increased compression for JPEG images (at the expense of compression performance)
Name: mozjpeg
Version: 3.2
Vendor: Mozilla Research
Release:el7.centos
URL: https://github.com/mozilla/mozjpeg
Group: System Environment/Libraries
Source0: https://github.com/mozilla/mozjpeg/archive/v%{version}.tar.gz
License: BSD-style
BuildRoot: %{_blddir}/%{name}-buildroot-%{version}-%{release}
BuildRequires: nasm
Prereq: /sbin/ldconfig
%if "%{_bits}" == "64"
Provides: %{name} = %{version}-%{release}, mozjpeg = %{version}-%{release}, libturbojpeg.so()(64bit)
%else
Provides: %{name} = %{version}-%{release}, mozjpeg = %{version}-%{release}, libturbojpeg.so
%endif

%description
mozjpeg is a fork of libjpeg-turbo that aims to speed up load times of web
pages by reducing the size (and, by extension, the transmission time) of JPEG
files.  It accomplishes this by enabling optimized Huffman trees and
progressive entropy coding by default in the JPEG compressor, as well as
splitting the spectrum of DCT coefficients into separate scans and using
Trellis quantisation.

Although it is based on libjpeg-turbo, mozjpeg is not intended to be a
general-purpose or high-performance JPEG library.  Its performance is highly
"asymmetric".  That is, the JPEG files it generates require much more time to
compress than to decompress.  When the default settings are used, mozjpeg is
considerably slower than libjpeg-turbo or even libjpeg at compressing images.
Thus, it is not generally suitable for real-time compression.  It is best used
as part of a web encoding workflow.

%prep
%setup -q -n mozjpeg-%{version}

%build
./configure prefix=%{_prefix} bindir=%{_bindir} datadir=%{_datadir} \
	docdir=%{_docdir} includedir=%{_includedir} libdir=%{_libdir} \
	mandir=%{_mandir} JPEG_LIB_VERSION=62 \
	SO_MAJOR_VERSION=62 SO_MINOR_VERSION=0 \
	--with-pic 
export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
make -j$NUMCPUS --load-average=$NUMCPUS DESTDIR=$RPM_BUILD_ROOT

%install

rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT docdir=%{_docdir} exampledir=%{_docdir}
rm -f $RPM_BUILD_ROOT%{_libdir}/*.la
/sbin/ldconfig -n $RPM_BUILD_ROOT%{_libdir}

%if 0

LJT_LIBDIR=/usr/bin/mozjpeg/lib64
if [ ! "$LJT_LIBDIR" = "%{_libdir}" ]; then
	echo ERROR: mozjpeg must be configured with libdir=%{_libdir} when generating an in-tree RPM for this architecture.
	exit 1
fi

%endif

LJT_DOCDIR=/usr/bin/mozjpeg/doc
if [ "%{_prefix}" = "/usr/bin/mozjpeg" -a "$LJT_DOCDIR" = "/usr/bin/mozjpeg/doc" ]; then
	ln -fs %{_docdir} $RPM_BUILD_ROOT/$LJT_DOCDIR
fi

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%dir %{_docdir}
%doc %{_docdir}/*
%dir %{_prefix}
%if "%{_prefix}" == "/usr/bin/mozjpeg" && "%{_docdir}" != "%{_prefix}/doc"
 %{_prefix}/doc
%endif
%dir %{_bindir}
%{_bindir}/cjpeg
%{_bindir}/djpeg
%{_bindir}/jpegtran
%{_bindir}/tjbench
%{_bindir}/rdjpgcom
%{_bindir}/wrjpgcom
%dir %{_libdir}
%{_libdir}/libjpeg.so.62.2.0
%{_libdir}/libjpeg.so.62
%{_libdir}/libjpeg.so
%{_libdir}/libjpeg.a
%{_libdir}/pkgconfig
%{_libdir}/pkgconfig/libjpeg.pc
%{_libdir}/libturbojpeg.so.0.1.0
%{_libdir}/libturbojpeg.so.0
%{_libdir}/libturbojpeg.so
%{_libdir}/libturbojpeg.a
%{_libdir}/pkgconfig/libturbojpeg.pc
%dir %{_includedir}
%{_includedir}/jconfig.h
%{_includedir}/jerror.h
%{_includedir}/jmorecfg.h
%{_includedir}/jpeglib.h
%{_includedir}/turbojpeg.h
%dir %{_mandir}
%dir %{_mandir}/man1
%{_mandir}/man1/cjpeg.1*
%{_mandir}/man1/djpeg.1*
%{_mandir}/man1/jpegtran.1*
%{_mandir}/man1/rdjpgcom.1*
%{_mandir}/man1/wrjpgcom.1*
%if "%{_prefix}" != "%{_datadir}"
 %dir %{_datadir}
%endif



%changelog


Just put it under your build environment in "SPECS" Directory. Download the SOURCE from https://github.com/mozilla/mozjpeg/archive/v3.2.tar.gz into the SOURCE directory.

Run "QA_RPATHS=0x0002 rpmbuild -bs /$PATHTOBUILDENV/rpmbuild/SPECS/mozjpeg.spec" to create the rpm.

Kind regards,

jopaha

**Comment by jopaha** [comment]
Hello @zevilz,
I have managed to build the RPM with the following SPECfile:

```
# Path under which mozjpeg should be installed
%define _prefix /usr/bin/mozjpeg

# Path under which executables should be installed
%define _bindir /usr/bin/mozjpeg/bin/

# Path under which Java classes and man pages should be installed
%define _datadir /usr/bin/mozjpeg/share

# Path under which docs should be installed
%define _docdir /usr/share/doc/%{name}-%{version}

# Path under which headers should be installed
%define _includedir /usr/bin/mozjpeg/include

%if "%{?__isa_bits:1}" == "1"
%define _bits %{__isa_bits}
%else
# RPM < 4.6
%if "%{_lib}" == "lib64"
%define _bits 64
%else
%define _bits 32
%endif
%endif

%if "%{_bits}" == "64"
%define _libdir %{_exec_prefix}/lib64
%else
%if "%{_prefix}" == "/usr/bin/mozjpeg"
%define _libdir %{_exec_prefix}/lib32
%endif
%endif

# Path under which man pages should be installed
%define _mandir /usr/bin/mozjpeg/share/man

Summary: A JPEG codec that provides increased compression for JPEG images (at the expense of compression performance)
Name: mozjpeg
Version: 3.2
Vendor: Mozilla Research
Release:el7.centos
URL: https://github.com/mozilla/mozjpeg
Group: System Environment/Libraries
Source0: https://github.com/mozilla/mozjpeg/archive/v%{version}.tar.gz
License: BSD-style
BuildRoot: %{_blddir}/%{name}-buildroot-%{version}-%{release}
BuildRequires: nasm
Prereq: /sbin/ldconfig
%if "%{_bits}" == "64"
Provides: %{name} = %{version}-%{release}, mozjpeg = %{version}-%{release}, libturbojpeg.so()(64bit)
%else
Provides: %{name} = %{version}-%{release}, mozjpeg = %{version}-%{release}, libturbojpeg.so
%endif

%description
mozjpeg is a fork of libjpeg-turbo that aims to speed up load times of web
pages by reducing the size (and, by extension, the transmission time) of JPEG
files.  It accomplishes this by enabling optimized Huffman trees and
progressive entropy coding by default in the JPEG compressor, as well as
splitting the spectrum of DCT coefficients into separate scans and using
Trellis quantisation.

Although it is based on libjpeg-turbo, mozjpeg is not intended to be a
general-purpose or high-performance JPEG library.  Its performance is highly
"asymmetric".  That is, the JPEG files it generates require much more time to
compress than to decompress.  When the default settings are used, mozjpeg is
considerably slower than libjpeg-turbo or even libjpeg at compressing images.
Thus, it is not generally suitable for real-time compression.  It is best used
as part of a web encoding workflow.

%prep
%setup -q -n mozjpeg-%{version}

%build
./configure prefix=%{_prefix} bindir=%{_bindir} datadir=%{_datadir} \
	docdir=%{_docdir} includedir=%{_includedir} libdir=%{_libdir} \
	mandir=%{_mandir} JPEG_LIB_VERSION=62 \
	SO_MAJOR_VERSION=62 SO_MINOR_VERSION=0 \
	--with-pic 
export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
make -j$NUMCPUS --load-average=$NUMCPUS DESTDIR=$RPM_BUILD_ROOT

%install

rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT docdir=%{_docdir} exampledir=%{_docdir}
rm -f $RPM_BUILD_ROOT%{_libdir}/*.la
/sbin/ldconfig -n $RPM_BUILD_ROOT%{_libdir}

%if 0

LJT_LIBDIR=/usr/bin/mozjpeg/lib64
if [ ! "$LJT_LIBDIR" = "%{_libdir}" ]; then
	echo ERROR: mozjpeg must be configured with libdir=%{_libdir} when generating an in-tree RPM for this architecture.
	exit 1
fi

%endif

LJT_DOCDIR=/usr/bin/mozjpeg/doc
if [ "%{_prefix}" = "/usr/bin/mozjpeg" -a "$LJT_DOCDIR" = "/usr/bin/mozjpeg/doc" ]; then
	ln -fs %{_docdir} $RPM_BUILD_ROOT/$LJT_DOCDIR
fi

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%dir %{_docdir}
%doc %{_docdir}/*
%dir %{_prefix}
%if "%{_prefix}" == "/usr/bin/mozjpeg" && "%{_docdir}" != "%{_prefix}/doc"
 %{_prefix}/doc
%endif
%dir %{_bindir}
%{_bindir}/cjpeg
%{_bindir}/djpeg
%{_bindir}/jpegtran
%{_bindir}/tjbench
%{_bindir}/rdjpgcom
%{_bindir}/wrjpgcom
%dir %{_libdir}
%{_libdir}/libjpeg.so.62.2.0
%{_libdir}/libjpeg.so.62
%{_libdir}/libjpeg.so
%{_libdir}/libjpeg.a
%{_libdir}/pkgconfig
%{_libdir}/pkgconfig/libjpeg.pc
%{_libdir}/libturbojpeg.so.0.1.0
%{_libdir}/libturbojpeg.so.0
%{_libdir}/libturbojpeg.so
%{_libdir}/libturbojpeg.a
%{_libdir}/pkgconfig/libturbojpeg.pc
%dir %{_includedir}
%{_includedir}/jconfig.h
%{_includedir}/jerror.h
%{_includedir}/jmorecfg.h
%{_includedir}/jpeglib.h
%{_includedir}/turbojpeg.h
%dir %{_mandir}
%dir %{_mandir}/man1
%{_mandir}/man1/cjpeg.1*
%{_mandir}/man1/djpeg.1*
%{_mandir}/man1/jpegtran.1*
%{_mandir}/man1/rdjpgcom.1*
%{_mandir}/man1/wrjpgcom.1*
%if "%{_prefix}" != "%{_datadir}"
 %dir %{_datadir}
%endif



%changelog
```


Just put it under your build environment in "SPECS" Directory. Download the SOURCE from https://github.com/mozilla/mozjpeg/archive/v3.2.tar.gz into the SOURCE directory.

Run "QA_RPATHS=0x0002 rpmbuild -bs /$PATHTOBUILDENV/rpmbuild/SPECS/mozjpeg.spec" to create the rpm.

Kind regards,

jopaha
