### ISSUE TITLE
An inquiry about the maximum size a MozJPEG image

### ISSUE THREAD

**Issue by amughrabi** [mozilla/mozjpeg#277]
I wish to have an answer about the maximum pixel dimensions of a MozJPEG image; for instance, what is the maximum image's width and height (W x H) for the source image before calling it via JNI or command line?

Thanks, 
Mughrabi

**Comment by kornelski** [comment]
65500x65500 pixels

**Comment by amughrabi** [comment]
Useful info, thanks @kornelski!

**Comment by amughrabi** [comment]
Hi @kornelski, In this [wiki page](https://en.wikipedia.org/wiki/JPEG) I found JPEG/JFIF supports a maximum image size of 65,535×65,535 pixels. Do we truncate 35 from each dimension to have an approximate value?

**Comment by kornelski** [comment]
The source code contains:

     #define JPEG_MAX_DIMENSION  65500L  /* a tad under 64K to prevent overflows */

**Comment by amughrabi** [comment]
Ah-ha! I thought it was an approximate value. Thanks, @kornelski!
