### ISSUE TITLE
cjpeg "Unrecognized input file format" for .jpg and .png on alpine linux in docker

### ISSUE THREAD

**Issue by wstoettinger** [mozilla/mozjpeg#279]
Hello! 

I am trying to integrate mozjpeg in my alpine docker container (following this tutorial: https://ariya.io/2016/03/using-mozjpeg-via-docker).  

The build works fine (with some warnings) and `jpegtran` seems to work but when i'm trying to use ´cjpeg`, no matter which parameters or files I use, i get the following error:
```
Unrecognized input file format --- perhaps you need -targa
```

I tried different jpg and png files, I tried mozjpeg v3.3.1 and v3.1 with default libjpeg v6 and libjpeg v8 (built with `--with-jpeg8`) but the error remains. 

Here is my build script:
```
git clone https://github.com/mozilla/mozjpeg.git
cd mozjpeg
git checkout v3.1
autoreconf -fiv
./configure --with-jpeg8 --prefix=/opt/mozjpeg
make install
```

when i call the `file` command on one of my jpg files, i get:

```
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, progressive, precision 8, 2880x1922, frames 3
```

so the system itself can identify the file as jpeg, but cjpeg can't.

PD: i get the same error, when downloading a precompiled version from https://mozjpeg.codelove.de/binaries.html

anyone got an idea?

Thanks in advance!

**Comment by kkopachev** [comment]
`cjpeg` supposed to compress jpeg. Does not look like it takes jpeg files as input. You probably want to do
`djpeg input.jpg | cjpeg -quality 80 -progressive -optimize > output.jpg`

**Comment by kornelski** [comment]
MozJPEG's `cjpeg` always supports JPEG as an input.

If you give it a JPEG and it wants a targa file, it means **it's not MozJPEG**. You're probably running an old plain cjpeg command that comes with your Linux distribution.

**Comment by wstoettinger** [comment]
@kornelski you were absolutely right! It just didn't came to my mind that Alpine could have it's own cjpeg given the small size of the distro.

Thanks for clarifying that!

**Comment by wstoettinger** [comment]
okay, Apline doesn't come with a cjpeg. one of my fellow devs added libjpeg turbo utils and I didn't realize it. *facepalm*

**Comment by pmioni** [comment]
Still have the bug on 
      "version": "4.3.1",
had to remove the 
```
              webp: {
                enabled: true
              }
```
 part of the configuration, even setting it to `false` didn't work.
