### ISSUE TITLE
how to read jpeg data? 

### ISSUE THREAD

**Issue by YHCodes** [mozilla/mozjpeg#283]
Hi, In the source file **example.c**, line 61 to 63, as below:
```
extertn JSAMPLE *image_buffer;
extern int image_height;
extern int image_width;
```
I don't know how handle or use what function to transform image file to image_buffer, image_height and image_width. 

can anybody give me some help, thanks very much for your help.

**Comment by kornelski** [comment]
Here's a tutorial: https://github.com/mozilla/mozjpeg/blob/master/libjpeg.txt

**Comment by YHCodes** [comment]
thanks @kornelski  , it helps
