### ISSUE TITLE
Error C2872: "boolean": Ambiguous Symbol jpeglib.h

### ISSUE THREAD

**Issue by YHCodes** [mozilla/mozjpeg#284]
I try to integrate mozjpeg to my project, I add some include files , `jpeg-static.lib` and `jpeg8.dll` from mozjpeg compiled files.

I supplied an interface to implement image compression, but when I use VS compile my project, it says that have 56 errors: `Error C2872: boolean : Ambiguous Symbol  jpeglib.h`

if you can tells me how to handle it, I will thank you very much!

**Comment by kornelski** [comment]
Ignore it. This name has been used in `jpeglib.h` since 1991.
