### ISSUE TITLE
Batch Processing Images

### ISSUE THREAD

**Issue by karanaggarwal1** [mozilla/mozjpeg#285]
Hi
Does MozJPEG process and compress multiple images at the same time? If so, then how can this be used as a feature? If not, what should I possibly to do in my code to make a pseudo implementation for this?

**Comment by kornelski** [comment]
MozJPEG is a library that is intended for internal use in other programs, like ImageMagick or GIMP, so batch capabilities should depend on what the MozJPEG-using program is capable of.

In the project there's also an outdated primitive demo tool that everyone happens to use instead. For everything about that tool the answer is "no" :)

**Comment by karanaggarwal1** [comment]
Thanks for the response
