### ISSUE TITLE
SSE/AVX for faster encoding?

### ISSUE THREAD

**Issue by roytam1** [mozilla/mozjpeg#286]
upstream has SSE/AVX improvements for faster encoding:
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/25
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/46

are they applicable to mozjpeg?

**Comment by kornelski** [comment]
Yes, to a small degree. When the improvements are released as stable, we'll merge them in.

**Comment by 2ji3150** [comment]
Looks like it's been released as stable on libjpeg-turbo 2.0.0.
