### ISSUE TITLE
build instructions for raspberry

### ISSUE THREAD

**Issue by wstoettinger** [mozilla/mozjpeg#288]
Hey there! 

is it possible to compile mozjpeg on a raspberry pi? i'm currently trying to build it on a RPi 3 Model B+ 

Since it can be compiled on an ARM architecture it should be possible! Would be nice to get a build recipe for it! 

thanks!

**Comment by kornelski** [comment]
It should work fine.

The build is exactly the same as for libjpeg-turbo, so search for instructions for libjpeg-turbo.

**Comment by wstoettinger** [comment]
thanks a lot! 
i managed to make it work already! apparently I was thinking too complicated. I searched for ARM in the build instructions and tried to adapt all the iPhone and Android recipes to match the raspberry instead of just running the build script without options. 

maybe somebody could mention raspberry in the build instructions for future reference?

**Comment by kornelski** [comment]
Great!
