### ISSUE TITLE
getting optimal settings for a given quality

### ISSUE THREAD

**Issue by hyperknot** [mozilla/mozjpeg#294]
I'm migrating away from a pipeline which used imagemagick resize -> TGA -> mozjpeg command line tool. I'm using vips now for it's huge performance bump, compared to imagemagick.

What I particularly enjoyed in mozjpeg's cjpeg tool was that it was auto-configuring the right settings based on quality input. I was using q=90 for reference images and q=75 for high-dpi web images.

Now, with vips I need to configure everything manually and I'm a bit lost.

Can you tell me which should I enable for my use case(q=90 reference + q=70 web high-dpi):

These are the options in VIPS:
- optimize-coding - Compute optimal Huffman coding tables, input gboolean
			default: false
- interlace    - Generate an interlaced (progressive) jpeg, input gboolean
			default: false
- no-subsample - Disable chroma subsample, input gboolean
			default: false
- trellis-quant - Apply trellis quantisation to each 8x8 block, input gboolean
			default: false
- overshoot-deringing - Apply overshooting to samples with extreme values, input gboolean
			default: false
- optimize-scans - Split the spectrum of DCT coefficients into separate scans, input gboolean
			default: false
- quant-table  - Use predefined quantization table with given index, input gint
			default: 0
			min: 0, max: 8

Should I enable _all_ of these options for optimal results? I guess for q=70 I shouldn't use `no-subsample` but maybe all others yes?

**Comment by kornelski** [comment]
* Optimize: yes
* interlace: yes
* no-subsample: no (subsample = yes)
* trellis: yes
* deringing: yes
* optimize scans: yes
* quant-table: 0 for low DPI, 3 for high-DPI.

**Comment by hyperknot** [comment]
Thanks a lot! All clear!

And what should I use for the q=90 reference image? This will be kept for a later date to generate new resampled sizes if needed. Disk space doesn't really matter, but processing speed does.

**Comment by kornelski** [comment]
Then use PNG, maybe? :)

For fast creation of bloated files, basically use inverse of all these settings. Don't optimize, don't subsample.

**Comment by hyperknot** [comment]
Thanks!
(Using PNG would be kind of overkill, and also super slow, but I get the point).
