### ISSUE TITLE
Unable to Use TurboJPEG Java wrapper

### ISSUE THREAD

**Issue by karanaggarwal1** [mozilla/mozjpeg#295]
Hi, 
I am trying to use MozJPEG for image compression in my Java Project, but it seems that there is some problem with the source code. I have downloaded the <a href="https://github.com/mozilla/mozjpeg/releases/download/v3.2/mozjpeg-3.2-release-source.tar.gz">mozjpeg-3.2.release.source.tar.gz</a> and did the following things to set it up:
<ol type="i">
<li><code>brew install jpeg-turbo nasm autoreconf automake libtool</code></li>
<li>Inside the extraction directory of mozjpeg, <code>./configure --with-java --host x86_64-apple-darwin NASM=/opt/local/bin/nasm \
  CFLAGS='-mmacosx-version-min=10.5 -O3' \
  LDFLAGS='-mmacosx-version-min=10.5'</code></li>
<li><code>sudo make && sudo make install</code></li>
</ol>
When I try to run the sample Java program given in the <code>java</code> folder,  I get the unsatisfied link error which say that it was unable to load the library from <code>/usr/lib/libturbojpeg.jnilib</code>. Upon digging further, I found that this library was in <code>/opt/libjpeg-turbo/lib32</code> and  <code>/opt/libjpeg-turbo/lib64</code>. In the <a href="https://github.com/mozilla/mozjpeg/blob/master/java/README">README</a> for java, it says that it should look in this path, whereas the compiled Java files in the <code>java/org/libjpegturbo/turbojpeg/</code> folder <code>(TJLoader.java)</code> show that the only paths that the program will search for are:
<ol>
<li><code>System.loadLibrary("turbojpeg")</code></li>
<li><code>System.load("/opt/mozjpeg/lib/libturbojpeg.jnilib")</code></li>
<li><code>System.load("/usr/lib/libturbojpeg.jnilib")</code></li>
</ol>
in case of Mac systems. Is there something that I am missing, or is there something to be changed in the documentation? Please help as I have been stuck on this for quite sometime. My Java version is 1.8 and I am using Mac OS X v10.10.

**Comment by kornelski** [comment]
I haven't used the Java interface. 

Have you been able to get the standard libjpeg-turbo library working? (i.e from libjpeg-turbo project, not from mozjpeg project?) 

I wonder if it's broken or poorly documented in general, or whether we've broken something in the fork.

**Comment by karanaggarwal1** [comment]
I haven't tried using that, but I have installed that library using homebrew so I suppose that should work perfectly fine. The associated library, <code>libturbojpeg.jnilib</code> has been installed on <code>/opt/libjpeg-turbo/lib32</code> and <code>/opt/libjpeg-turbo/lib64</code> as they say in their documentation. I don't know what else is required. Have a look at <a href=https://codeshare.io/2BP01L>this</a> code I got after building the mozjpeg library for the TJLoader.java class. According to this, the paths that would be looked upon for Mac systems would be <code>/opt/mozjpeg/lib/libturbojpeg.jnilib</code> and <code>/usr/lib/libturbojpeg.jnilib</code> but the <a href="https://github.com/mozilla/mozjpeg/blob/master/java/README">documentation</a> in this repository says that the paths <code>/opt/libjpeg-turbo/lib32</code> and <code>/opt/libjpeg-turbo/lib64</code> would be explored. Is something wrong over here?
