### ISSUE TITLE
jpegtran prefers input file if it has smaller size by default

### ISSUE THREAD

**Issue by kkopachev** [mozilla/mozjpeg#296]
I have a progressive input.jpg with 10 scans. I would like to supply custom scans file and save image progressive, but with another scans configuration. 
```
./jpegtran -debug -copy none -optimize -scans scans.txt -outfile mozjpegtran-new.jpg input.jpg
```

As a result, I expect progressive file with specified scans.

Actual result is just straight copy of input file. 
I managed to figure out that if force this if to false state
https://github.com/mozilla/mozjpeg/blob/7678cba14037c9381119df6c6452e18f70ccb327/jpegtran.c#L569-L575
, disabling `jpeg_mem_dst`, it all works as expected. 

This is causing https://github.com/mozilla/mozjpeg/issues/221 and most likely https://github.com/mozilla/mozjpeg/issues/174 as I was able to repro it with non-arithmetic coded image.

**Comment by kkopachev** [comment]
Looked deeper into this and realized that lines posted above are not the cause, but just a flag. 
If not using `jpeg_mem_dest`, then `outsize` is never updated and remains 0. Then, right before outputting to destination file, jpegtran checks if output is bigger than input and swaps buffer pointer, causing input file to be written out.
https://github.com/mozilla/mozjpeg/blob/7678cba14037c9381119df6c6452e18f70ccb327/jpegtran.c#L600-L603

That's not intuitive behavior, since I'd expect jpegtran do lossless transformations and output whatever result is, instead of silently outputting input file.

**Comment by kkopachev** [comment]
I'd submit a PR, but straggle to chose what should be done in that case. Some opinions would be great to have here. 
I could probably add a check that any image-changing arguments is passed on command line, but not sure if that would be acceptable fix.

**Comment by kornelski** [comment]
First, if libjpeg-turbo has the same bug, then please submit the PR there.

It seems sensible that options which change image visually force saving even if the image is larger.

**Comment by kkopachev** [comment]
libjpeg-turbo does not have this code, hence issue here. I'll come up with PR soon.

**Comment by kornelski** [comment]
ok, thanks!
