### ISSUE TITLE
Some .jpg files are not compressed good enough

### ISSUE THREAD

**Issue by yesworld** [mozilla/mozjpeg#304]
Hi,

I use [mozjpeg-bin](https://www.npmjs.com/package/mozjpeg) to ensure that the Google speed test service gives a good rating for the quality of the photos. Most of the photos were compressed, but some of them are not good enough.

Example:
Origin 75,1Kb 
![](https://upload.realnoevremya.ru/test-photo/nominees_origin.jpg)

mozjpeg 50,2Kb (options: {quality: 65} )
![](https://upload.realnoevremya.ru/test-photo/nominees_loader.jpg)

Compressed by google 2,5Kb
![](https://upload.realnoevremya.ru/test-photo/nominees_google.jpg)

What's wrong? :(

```js
var execFile = require('child_process').execFile;
var mozjpeg = require('mozjpeg');

execFile(mozjpeg, ['-quality', '65', '-outfile', './output.jpg', './origin.jpg'], function (err) {
  console.log('Image minified!', err);
});
```

>Node v8.11.3
>mozjpeg v4.1.1

**Comment by kornelski** [comment]
90% of the file is taken by hidden metadata added by Adobe Photoshop CC. You can use `jpegtran --strip-all` to get rid of it.
