### ISSUE TITLE
Misdecoded image in buffered mode

### ISSUE THREAD

**Issue by diegosanchezr** [mozilla/mozjpeg#305]
I've jumped into an issue where [an image](https://user-images.githubusercontent.com/6777207/45326711-995dbf80-b54c-11e8-970f-7c360218fb86.jpg) is being decoded incorrectly. In particular, the image appears grayscale.

This is my code (sorry for the Objective-C bits). I'm passing the full image data and scanNumber >=8 (the image has 8 scans).

```
static NSData *kDecodeImage(NSData *data, int scanNumber)
{
  struct jpeg_decompress_struct cinfo;
  struct jpeg_error_mgr jpeg_error_mgr;
  cinfo.err = jpeg_std_error(&jpeg_error_mgr);

  jpeg_create_decompress(&cinfo);
  jpeg_mem_src(&cinfo, (unsigned char *)data.bytes, data.length);
  jpeg_read_header(&cinfo, TRUE);
  cinfo.do_block_smoothing = NO;
  cinfo.do_fancy_upsampling = NO;
  cinfo.dct_method = JDCT_FASTEST;
  cinfo.out_color_space = JCS_EXT_RGB;
  cinfo.buffered_image = scanNumber > 0;

  jpeg_start_decompress(&cinfo);

  size_t outputSize = cinfo.output_width * cinfo.output_height * 3;
  NSMutableData *output = [NSMutableData dataWithLength:outputSize];
  unsigned char *buffer = (unsigned char *)output.mutableBytes;

  // Uncomment this lines and image is rendered properly 🤔
  //  int status;
  //  do {
  //    status = jpeg_consume_input(&cinfo);
  //  } while ((status != JPEG_SUSPENDED) && (status != JPEG_REACHED_EOI) && cinfo.input_scan_number < scanNumber );

  jpeg_start_output(&cinfo, scanNumber);

  while (cinfo.output_scanline < cinfo.output_height) {
    unsigned char *outputScanArray[1];
    memset(outputScanArray, 0, sizeof(outputScanArray));
    outputScanArray[0] = buffer + ((cinfo.output_scanline) * cinfo.output_width * 3);
    if (jpeg_read_scanlines(&cinfo, (JSAMPARRAY)outputScanArray, 1) < 1) {
      return nil;
    }
  }

  jpeg_finish_output(&cinfo);
  jpeg_finish_decompress(&cinfo);
  jpeg_destroy_decompress(&cinfo);

  return output;
}
```

Some notes:
- If I uncomment the jpeg_consume_input loop, the image is decoded properly
- If I decode one scan at a time (doing jpeg_start_output(&cinfo, i)...jpeg_finish_output(&cinfo), i = 1...8, then the image is also decoded properly for the final scan.
- If I disable buffering (buffered_image = false, remove jpeg_start_output and jpeg_finish_output) then the image is again decoded properly

What's wrong with this particular image? Am I doing something wrong, or am I expected to have the jpeg_consume_input loop when in buffered mode? Other images work just fine.

Thanks!

**Comment by kornelski** [comment]
Can you reproduce the bug with libjpeg-turbo?

**Comment by diegosanchezr** [comment]
Yes, it also happens with libjpeg-turbo 2.0.0. Just created the same issue there: https://github.com/libjpeg-turbo/libjpeg-turbo/issues/279

**Comment by kornelski** [comment]
OK, we'll get that fix when it's fixed in libjpeg-turbo.
