### ISSUE TITLE
libjpeg-turbo 2.0

### ISSUE THREAD

**Issue by davidenco** [mozilla/mozjpeg#306]
libjpeg-turbo 2.0 has been released! Can it be integrated please?

https://github.com/libjpeg-turbo/libjpeg-turbo/releases

**Comment by kornelski** [comment]
Sure. 

I'm going on holidays, so I won't do it in the next few weeks. 

Would you like to give it a try?

It will have scary looking merge conflicts in build and readme files due to renaming of libjpeg to mozjpeg, but these aren't hard to resolve.

**Comment by xinyu391** [comment]
@davidenco  
I have merge turbo2.0 ,https://github.com/xinyu391/mozjpeg.
the jpeg6b api is works fine. before the official version, you could try this .

**Comment by kornelski** [comment]
It's on master. Please test it.

**Comment by 2ji3150** [comment]
mozjpeg 3.4.0 tested with no problem. It's faster. Thanks for the great work!

**Comment by davidenco** [comment]
Since master was updated, autoreconf no longer works because configure.ac or configure.in is missing!

**Comment by davidenco** [comment]
My apologies. I have used cmake now and all is well.
