### ISSUE TITLE
cjpeg -quality

### ISSUE THREAD

**Issue by 781545872** [mozilla/mozjpeg#307]
I want to compress an image to specified quality，so I run 'cjpeg -quality 80 -outfile t1.jpeg t.jpeg'.
And I use identify(from ImageMagick) to caluculate quality of the output image and input image.
The quality of 't.jpeg' is 99.However,the quality of 't1.jpeg' is 50, not 80.
Why?

**Comment by kornelski** [comment]
ImageMagick doesn't calculate quality correctly. It has a hack that only matches old libjpeg and nothing else.

**Comment by 781545872** [comment]
And how can I get the quality of a jpeg format image?

**Comment by 781545872** [comment]
Thank you for answering my question.I'll close the issue.
