### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by cuva** [mozilla/mozjpeg#310]
Hi,

First of all, thanks for the great library!

Would you be open in accepting a PR adding [cocoapods](https://cocoapods.org) support for Mozjpeg? Cocoapods is a dependency manager for iOS projects which would make the library's integration a no brainer and should only require adding a single file to the repo.

Thanks!

**Comment by cuva** [comment]
Thanks for your quick answer @kornelski.

Couldn't agree more. Since C is interoperable with Objective-C, I'd suggest first and foremost defining a `mozjpeg` pod to enable it being integrated through Cocoapods as-is. 

As you've mentioned, It would then open the door for a higher-level Objective-C/Swift compatible framework that exposes idiomatic platform APIs depending on mozjpeg's C library through CP. 

In practice, adding support for CP simply requires adding a `.podspec` [file at the root of the repo](https://guides.cocoapods.org/syntax/podspec.html). As the podspec contains the library's version number, running `pod repo update` when releasing a new version would be the only command required to push an updated version of the spec to their [centralised spec repository](https://github.com/CocoaPods/Specs).

I've got a working podspec locally - so happy to push a PR if that's ok with you and get into more details there!?

**Comment by kornelski** [comment]
Yes, great! I'm happy to add a podspec.
