### ISSUE TITLE
Unable to read PNG and BMP(imagemagick) 

### ISSUE THREAD

**Issue by 2ji3150** [mozilla/mozjpeg#318]
build with the latest mozjpeg 3.4 using on latest windows 10

when Using with cjpeg to convert PNG, it shows:
`Unrecognized input file format --- perhaps you need -targa`
after add `-targa` still not work

when Using cjpeg to convert BMP generated from famous ImageMagick generated (for example: resize by ImageMagick)
`Invalid BMP file: bad header length`

Here is an exapmle BMP file which cant not be converted.
https://www.dropbox.com/s/6ip8pr0s5yazt0r/ex.bmp?dl=0

#190

**Comment by kornelski** [comment]
Indeed, only an older version of BMP is supported. Try exporting TGA from ImageMagick.

**Comment by dmak** [comment]
You have commented [here](https://github.com/mozilla/mozjpeg/issues/332#issuecomment-486441772) that PNG library detect on CMake does not work. Any plans to fix that?

What are the workarounds? I have added
```
set(PNG_SUPPORTED "1")
```
to `CMakeLists.txt` but it builds only `cjpeg-static` with PNG support.

**Comment by dmak** [comment]
My excuses for off-topic, but did somebody managed to build mozjpeg under Debian x64? I tried to follow [the instructions](https://github.com/mozilla/mozjpeg/blob/master/BUILDING.md#32-bit-build-on-64-bit-linuxunixmac) but I failed (supposing current directory is cloned Git tree):
```
$ export CFLAGS=-m32 LDFLAGS=-m32                                                                  
$ cmake -G"Unix Makefiles" .                                                                       
CMake Error at CMakeLists.txt:7 (project):
  Generator

    Unix Makefiles

  does not support platform specification, but platform

    x32

  was specified.
```
I have GCC x32 installed:
```
$ dpkg -l | grep gcc
ii  gcc               4:8.3.0-1  amd64  GNU C compiler
ii  gcc-8-base:amd64  8.3.0-6    amd64  GCC, the GNU Compiler Collection (base package)
ii  gcc-8-base:i386   8.3.0-6    i386   GCC, the GNU Compiler Collection (base package)
ii  libgcc1:amd64     1:8.3.0-6  amd64  GCC support library
ii  libgcc1:i386      1:8.3.0-6  i386   GCC support library
```
Also I have noticed that [these build instructions](https://github.com/mozilla/mozjpeg/blob/master/BUILDING.txt#L98) contain the step to run `autoreconf` which does not work:
```
$ autoreconf -fiv
autoreconf: 'configure.ac' or 'configure.in' is required
```

**Comment by kornelski** [comment]
Sorry, I don't know much about cmake.

The build system is from libjpeg-turbo, and libjpeg-turbo may have some docs about cross-compilation.

**Comment by dmak** [comment]
Then how do you build the library? I would like to verify that PNG input now works (this very issue), but I simply cannot build it...

**Comment by kornelski** [comment]
You seem to be trying to cross-compile it, which is 10 times more complicated than simply build it. If you have a 64-bit OS, try building it for 64-bit (i.e. just build it, don't force 32-bitness anywhere).

**Comment by dmak** [comment]
I am happy to compile it for x64, but it fails with the same error:
```
$ unset CFLAGS LDFLAGS 
$ cmake -G"Unix Makefiles" .
CMake Error at CMakeLists.txt:7 (project):
  Generator

    Unix Makefiles

  does not support platform specification, but platform

    x32

  was specified.

-- Configuring incomplete, errors occurred!
```
