### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by polarathene** [mozilla/mozjpeg#321]
Last release was in Mar 2018 240 commits ago? I see that in Nov 2018 [libjpeg-turbo 2.0 got merged](https://github.com/mozilla/mozjpeg/issues/306), there is a commit about tagging 2.0.0, but there is no actual tag in the repo matching that?

As this is the release that drops autotools moving those installs to use CMake instead(according to the [2.0.0 changelog](https://github.com/mozilla/mozjpeg/blob/master/ChangeLog.md)), it'd be handy to have a release to build from rather than master.

I didn't notice any milestone/roadmap listing what was to be done for this release, so I'm not sure if it's waiting on anything?

**Comment by kornelski** [comment]
Due to change to cmake it's a major breaking release. I've been busy updating my tools to the latest version.

If you'd like to help, please use code from master and verify that it's working for you.

**Comment by polarathene** [comment]
@kornelski I have already built from master to use with alpine 3.8 and debian-stretch docker images. Appears to be working fine apart from not knowing how to enable PNG support with CMake.

I should have the docker images in a repo tomorrow and get them on DockerHub if you'd like to try them. I have made a PR to another users Dockerfile(alpine based), it's more simple than my personal one but builds mozjpeg pretty much the same way: https://github.com/polarathene/mozjpeg-docker/blob/patch-1/Dockerfile

> Due to change to cmake it's a major breaking release.

So it will be 4.0.0 instead of 3.4.0?

**Comment by fhanau** [comment]
I recently updated the version of mozjpeg I use to master and did not encounter any issues with jpegtran-like behaviour. I didn't have any issues with the new build system.

**Comment by zvezdochiot** [comment]
Backport for other provided?

**Comment by polarathene** [comment]
> So it will be 4.0.0 instead of 3.4.0?

[Confirmed](https://github.com/mozilla/mozjpeg/commit/426de82d0c081c996c23b75fed05833b6627b590).

**Comment by caoli5288** [comment]
Wait for new release
