### ISSUE TITLE
Slow to decode a corrupted jpeg file

### ISSUE THREAD

**Issue by HongxuChen** [mozilla/mozjpeg#324]
It is similar to [the one in libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/328), but the performance seems worse.

```
$ time ./mozjpeg/BUILD/djpeg-static -gif -outfile /tmp/test.gif h01.jpeg
Corrupt JPEG data: 4 extraneous bytes before marker 0xda

real    45.17s
user    19.25s
sys     3.29s
```

![h01.jpeg](https://user-images.githubusercontent.com/843267/52468581-240e1d80-2bc4-11e9-8d73-c91363dccbb3.jpeg)

**Comment by kornelski** [comment]
We don't have custom decoding code, so we'll have it fixed when libjpeg-turbo fixes it.
