### ISSUE TITLE
Trouble for build on iOS

### ISSUE THREAD

**Issue by wolfviking0** [mozilla/mozjpeg#33]
Hi,

I'm trying to build on iOS, but I have some trouble, I am on Maverick 10.9.2 + xcode 5.1, I reinstall an older version of xcode (Xcode 4.5) and call sudo xcode-select -switch /Applications/Xcode45.app/

Following the BUILDING.txt, I try to build for armv7, I just change the IOS_PLATFORMDIR with IOS_PLATFORMDIR="/Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform"

When I call sh configure with all parameter, I have this error :
configure: error: C preprocessor "/lib/cpp

What am I doing wrong ??

------ CONSOLE ------ 
sh /Users/aliot/Desktop/actisku/engine/software/sdk/mozjpeg/source/configure --host arm-apple-darwin10 --enable-static --disable-shared CC=/Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 LD=/Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 CFLAGS="-mfloat-abi=softfp -isysroot /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.0.sdk -O3 -march=armv7 -mcpu=cortex-a8 -mtune=cortex-a8 -mfpu=neon" LDFLAGS="-mfloat-abi=softfp -isysroot /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.0.sdk -march=armv7 -mcpu=cortex-a8 -mtune=cortex-a8 -mfpu=neon"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin10-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /Users/aliot/Desktop/actisku/engine/software/sdk/mozjpeg/source/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for arm-apple-darwin10-gcc... /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 accepts -g... yes
checking for /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 option to accept ISO C89... none needed
checking whether /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 understands -c and -o together... yes
checking dependency style of /Applications/Xcode45.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/arm-apple-darwin10-llvm-gcc-4.2... gcc3
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/Users/aliot/Desktop/actisku/engine/software/sdk/mozjpeg/temp':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

**Comment by pornel** [comment]
Sorry, this got accidentally closed when libjpeg-turbo commits were merged. However, since newer libjpeg-turbo does include fixes for iOS, this may actually resolve this issue.

Please feel free to reopen if there's still a problem.
