### ISSUE TITLE
Write past end of array in jpeg_simple_progression()

### ISSUE THREAD

**Issue by martincmartin** [mozilla/mozjpeg#333]
When allocating memory for the scans, we limit the allocation to 10 scans:

https://github.com/mozilla/mozjpeg/blob/master/jcparam.c#L905

However, nscans can be 11 (see earlier in the same function), and it looks like all of them are written.

The MAX with 10 comes from libjpeg-turbo, which has simpler logic to set nscans and doesn't have the 11 case.

In general, the max seems odd: if nscans is bigger, we silently allocate less memory that we need, and proceed to overwrite the end of the array.

**Comment by lambdapioneer** [comment]
Hey @martincmartin 👋

It's `MAX`, right? So it would be allocating space for 11 elements if `nscans==11`. I remember fixing some parts in these lines, and this is correct afaict.

**Comment by martincmartin** [comment]
@lambdapioneer D'oh!  Although it clearly says MAX, I somehow read it as min.  My bad, sorry.

Maybe change the 10 to 11?  Not a correctness issue, but the intention seems to be to avoid reallocations, so setting it to the largest of the commonly used values seems appropriate.  Pretty minor point though.

Sorry to waste your time.
