### ISSUE TITLE
Available for Windows 10 UWP?

### ISSUE THREAD

**Issue by daramkun** [mozilla/mozjpeg#334]
I have no idea how can I build mozjpeg dynamic or static library for UWP.

How can I build for UWP?

**Comment by daramkun** [comment]
Found method for use in Windows 10 UWP. Same way for x86 and x64 but ARM and ARM64 is not available because libjpeg-turbo is not support ARM&ARM64 for Windows.

https://github.com/libjpeg-turbo/libjpeg-turbo/issues/69

**Comment by ValZapod** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/69#issuecomment-759156538
It is done upstream 10 hours ago.
