### ISSUE TITLE
Lossless  convert png example

### ISSUE THREAD

**Issue by patrickkh7788** [mozilla/mozjpeg#339]
Hi,

I am able to load png into raw buffer array,  and I need use mozJpeg to convert it into jpeg lossless without loss 1 byte information.

How do it do it ? I search the document and example but get nothings.  please help ...

**Comment by patrickkh7788** [comment]
I try use ` /usr/local/opt/mozjpeg/bin/jpegtran /usr/local/opt/mozjpeg/bin/jpegtran -copy none -outfile`, but it report Not a JPEG file: starts with 0x89 0x50

**Comment by zvezdochiot** [comment]
@patrickkh7788 say> (png) convert it into jpeg lossless

Mission impossible!

**Comment by patrickkh7788** [comment]
convert raw image binary (Rgb with alpha=0) to lossless jpg is impossible with  mozcjpeg ?  or there is not possible at any other software ?

**Comment by zvezdochiot** [comment]
@patrickkh7788 say> or is not possible at any other software

Absolutely right!
```
(double)DCT -> (int)DCT
(int)DCT != (double)DCT
```

**Comment by patrickkh7788** [comment]
thanks for explain.
