### ISSUE TITLE
Remove Facebook embedded tracking data

### ISSUE THREAD

**Issue by vatterspun** [mozilla/mozjpeg#340]
This is less of a technical issue and more of a advocacy/privacy issue so if it's out of scope, please close the issue.  It also only represents a few bytes of a given file, but removing useless data would certainly reduce file size:

https://techstartups.com/2019/07/13/facebook-embedding-tracking-data-inside-photos-download/

Mozilla has been very good about pushing back against Facebook tracking over the last two years (e.g. the Facebook Container) so I thought this might be something project owners would be interested in.

**Comment by dwbuiten** [comment]
I'm not sure how this is applicable to mozjpeg, given that mozjpeg is an encoder, and wouldn't carry through tags anyway?

**Comment by Furniel** [comment]
Здравствуйте ыцл рот  ли ц н ног 6и6  ли не шлто ш то 7ц но оо о г 6и6 66р66ои то 6г 617грн т5 н 67 о ли ли и лот р6н по оштл6п6щщщ ценз ы

**Comment by vatterspun** [comment]
> given that mozjpeg is an encoder

It's a little more than an encoder.  Currently, mozjpeg leaves metadata intact by default, but this can be modified via _-copy_ none/comments/all (https://github.com/mozilla/mozjpeg/blob/master/usage.txt).  Although metadata has many opsitive uses, this can take up anywhere from 1-10% of the total file size and can harm creator privacy, so it's usually ideal to remove it when sharing with non-photographers or image editors.

> wouldn't carry through tags anyway?

This is a feature request because the embedded data in question doesn't represent image data nor metadata, but a sort of file hash usable only by one company (Facebook).  The mozjpeg has been very successful at pulling out absolutely everything unnecessary to squeeze files without data loss, this information (if identified) could be removed without harming image data.  

Effort here could pay off in the future: although it's not the same company it was even a year ago, Facebook still sets market trends.  While the data in question is currently very small, I suspect that more companies will follow suit and add their own non-image data that may stack.  Efforts to find and eliminate any wasteful and privacy-harming data now may save lots of disk space and bandwidth over time.

**Comment by kornelski** [comment]
I don't disagree about role of metadata, but I think you're misplacing responsibility for it on mozjpeg. 

Mozjpeg first and foremost, is a library. It's often mistaken for being `jpegtran` and `cjpeg`, but these are actually only very old demo tools for the library, and they're kinda crap (don't use them, compile mozjpeg into proper graphics programs). And they already have options to strip metadata, anyway.

Mozjpeg as an encoder is passive. It stores the data it's told to store. If a program says "store this data", mozjpeg stores it. It could be uncooperative about this, but it's like expecting a text editor to refuse to type swearwords.

It's not going to stop Facebook from doing whatever they want to do to files they generate. Facebook has ability and resources to remove any limitation from mozjpeg that doesn't suit their goals.

**Comment by vatterspun** [comment]
> you're misplacing responsibility for it on mozjpeg 

I'm not trying to assign responsibility, only make the case for inclusion.

... Facebook has ability and resources to remove any limitation from mozjpeg that doesn't suit their goals.

Mozjpeg as an encoder is passive. It stores the data it's told to store. If a program says "store this data", mozjpeg stores it. It could be uncooperative about this, but it's like expecting a text editor to refuse to type swearwords.
I'm confused: the encoder can remove some types of non-essential data from a file (e.g. metadata) but not 


There's no question that mozjpeg certainly can't fix this issue and whatever items that are to come, but it can certainly help.  Every image that doesn't have this junk tag means less privacy-harming user data for these companies. 

> it's like expecting a text editor to refuse to type swearwords

My suggestion (maybe a foolish one) is that if the program can modify/eliminate non-image information (such as EXIF metatdata), why not 

By weird coincidence I've actually written up something that flags swear words from documents, but I think I understand what you're saying.

Look you obviously know more about this than I do so please feel free to close the issue.  I'm just not sure who else I would contact to try and eliminate this junk data.


If the goals of are to maintain JPEG as a standard until , maybe it should be less passive.

It certainly might be out of scope.

**Comment by kornelski** [comment]
There are already tools based on MozJPEG that remove junk from files, I even [develop one](https://imageoptim.com).

What I mean is MozJPEG is a low-level library that does what it's told. If it's told to store metadata, it doesn't make sense for MozJPEG to judge whether that metadata is good or bad. It can't drop support for storing any metadata, because there are useful, legitimate uses for it. Programs that don't want to store metadata, already have option to do so. Programs that want to use MozJPEG to remove metadata, already have an option to do so.

**Comment by vatterspun** [comment]
> There are already tools based on MozJPEG that remove junk from files, I even develop one.

The fact that you develop multiple encoding tools didn't escape my notice.  

Anyway, the overall suggestion here appears to be out of scope so I'll go ahead and close.
