### ISSUE TITLE
support -drop in jpegtran

### ISSUE THREAD

**Issue by lovasoa** [mozilla/mozjpeg#343]
The original jpegtran has a nice `-drop` option that allows joining two jpeg files together losslessly:
https://jpegclub.org/jpegtran/

Would it be in the scope of this project to implement the same in mozjpeg ?

**Comment by kornelski** [comment]
This looks like an extension from the "v9" fork of libjpeg. 

I'd prefer to keep MozJPEG as close as possible to libjpeg-turbo, so try getting the change into libjpeg-turbo.

**Comment by lovasoa** [comment]
It looks like it has been proposed to libjpeg-turbo, and refused in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/71.

Does that mean it has no chance of being integrated in mozjpeg ? That would be a pitty, because I think it is so only piece of code that allows joining jpeg files losslessly, and it's old and unmaintained.

**Comment by kornelski** [comment]
Adding it to MozJPEG wouldn't change anything about it being old and unmaintained. MozJPEG would be worse off for having more old and unmaintained code.
