### ISSUE TITLE
[Help Wanted] Error when Building on Mac

### ISSUE THREAD

**Issue by fabricezhang** [mozilla/mozjpeg#347]
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
/Users/xx/Documents/work/mozjpeg/simd/x86_64/jsimdcpu.asm:67: error: symbol `JSIMD_AVX2' undefined
/Users/xx/Documents/work/mozjpeg/simd/x86_64/jsimdcpu.asm:69: error: label `_jpeg_simd_cpu_support.return' changed during code generation [-w+error=label-redef-late]
make[2]: *** [simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[1]: *** [simd/CMakeFiles/simd.dir/all] Error 2
make: *** [all] Error 2

I got this error while trying to compile mozjpeg on mac.
I typed 
cmake -G"Unix Makefiles" .
and then make

Besides, I can build this project successfully for 1.x version with autotool and also I can build libjpeg-turbo successfully for both (1.x and 2.0.3) version.
Does anybody can give me some tips? I just failed to get answer from google.
Thanks in advance.

**Comment by kornelski** [comment]
You need to install `nasm`. It's available from Homebrew.

There's also a version of `nasm` in Xcode, but it's so old and crappy that it's useless. You need to install a working version of `nasm`.

**Comment by fabricezhang** [comment]
> You need to install `nasm`. It's available from Homebrew.
> 
> There's also a version of `nasm` in Xcode, but it's so old and crappy that it's useless. You need to install a working version of `nasm` not from Apple.

Hi kornelski, 
Thank you for your time 
But I installed `nasm` by homebrew and the version is 
`NASM version 2.14.02 compiled on Dec 27 2018`, is it correct ? I think the this is the latest release of NASM.

**Comment by kornelski** [comment]
Yes, this one should be fine. Is it still failing with it installed?

**Comment by fabricezhang** [comment]
> Yes, this one should be fine. Is it still failing with it installed?

Yes, still the same error. But I can build libjpeg-turbo 2.0.3 sucessfully, does it mean that my environment is well set-up?

**Comment by kornelski** [comment]
It's surprising that libjpeg-turbo 2 builds for you, because the build system for both is almost the same, and the SIMD part is absolutely identical.

Have you tried deleting the build directory and generating makefiles again? Make cmake has picked a wrong nasm previously.

**Comment by fabricezhang** [comment]
> It's surprising that libjpeg-turbo 2 builds for you, because the build system for both is almost the same, and the SIMD part is absolutely identical.
> 
> Have you tried deleting the build directory and generating makefiles again? Make cmake has picked a wrong nasm previously.

I clone a new repo and I can build mozjpeg successfully now.  I think that I miss some files when I clean the folder. ( I used git clean -df).

but when I try build with ndk, there's a new issue occurs, 

> CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) (Required is
  at least version "1.6") 

My build script works for libjpeg-turbo 2.0.3 (see below),  and the libpng is installed by homebrew.

```
NDK_PATH=${NDK_HOME}
TOOLCHAIN=clang
ANDROID_VERSION=14

echo $JAVA_HOME

cmake -G"Unix Makefiles" \
  -DANDROID_ABI=armeabi-v7a \
  -DANDROID_ARM_MODE=arm \
  -DANDROID_PLATFORM=android-${ANDROID_VERSION} \
  -DANDROID_TOOLCHAIN=${TOOLCHAIN} \
  -DCMAKE_ASM_FLAGS="--target=aarch64-linux-android${ANDROID_VERSION}" \
  -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}/build/cmake/android.toolchain.cmake \
  ..

make
```
 
Have you met this issue before? Is it caused by Mac Mojave? I didn't find any reference on google.

Thank you so much.

**Comment by kornelski** [comment]
the cmake script wants to control whether libpng is linked dynamically or statically, but cmake is not sophisticated enough for this, so it's half-broken. You need to specify exact location for libpng, and possibly zlib too, as a defined variable.
