### ISSUE TITLE
jpegtran crop image not accurate？

### ISSUE THREAD

**Issue by JaosonMa** [mozilla/mozjpeg#348]
step1:  use cjpeg.exe to compress an image with cmd
cjpeg.exe -baseline -optimize -quality 10 -outfile ..\4096_2.jpg ..\4096.jpg
step2: crop rect from the output 4096_2.jpg with the Rectangular coordinates by jpegtran.exe
jpegtran.exe -crop 440x430+182+255 -outfile ..\006961_crop.jpg ..\006961.jpg
here is the problem , 
the output image size is not 440x430 it is 446x445 ，
and the x,y is not (182.255), is was(171,240)
so the output crop image have deviation from the （182,255,440,430），Causing errors in my follow-up procedures
-----------------------------------------
how can i crop the image just with the box(182,255,440,430) ?
is there some cmd that can realization this?  
please help thanks a lot!

PS:
i can use opencv crop the (182,255,440,430) ,it is Very accurate, no error in one pixel. but with opencv  The output image will become larger，so i must use the jpegtran to crop .

@Calinou @kornelski

**Comment by JaosonMa** [comment]
i just found  use -crop 440fx430f+182+255 can make sure the output image size is (440x430) ，but the pos(182,255) is not right 。 how can i make the pos(x,y) not change in the code ?

**Comment by JaosonMa** [comment]
@Calinou  @kornelski 
when i debug the code , found that info->iMCU_sample_width = 16 
and some thing was done with this , 
how i can jump this code ,

**Comment by zvezdochiot** [comment]
```sh
$ echo "182%8" | bc # != 0 (bad)
6
$ echo "255%8" | bc # != 0 (bad)
7
$ echo "440%8" | bc # == 0 (good)
0
$ echo "430%8" | bc # != 0 (bad)
6
```
See jpeg specification.

**Comment by JaosonMa** [comment]
> ```shell
> $ echo "182%8" | bc # != 0 (bad)
> 6
> $ echo "255%8" | bc # != 0 (bad)
> 7
> $ echo "440%8" | bc # == 0 (good)
> 0
> $ echo "430%8" | bc # != 0 (bad)
> 6
> ```
> 
> See jpeg specification.

you mean that the (x,y,w,h)must be the multiple of  8? 

if so ,does it mean mozjpeg cant not Realization crop a rectangle accurate with no error in one pixel?

**Comment by zvezdochiot** [comment]
@JaosonMa say:
>does it mean mozjpeg cant not Realization crop a rectangle accurate with no error in one pixel?

This means that jpeg is encoded in 8x8 blocks and does not include arbitrary trimming. If the right and bottom blocks have a clipping mechanism, then the left and top blocks do not.

Mozjpeg has nothing to do with it. See jpeg specification.

**Comment by JaosonMa** [comment]
> @JaosonMa say:
> 
> > does it mean mozjpeg cant not Realization crop a rectangle accurate with no error in one pixel?
> 
> This means that jpeg is encoded in 8x8 blocks and does not include arbitrary trimming. If the right and bottom blocks have a clipping mechanism, then the left and top blocks do not.
> 
> Mozjpeg has nothing to do with it. See jpeg specification.

I'm not very proficient in JPEG compression，but the info you provied can slove my problem, i change my box pos before crop, make x,y,w,h was the multiple of 8 . that works well .
thank you
