### ISSUE TITLE
PNG support still broken

### ISSUE THREAD

**Issue by Beep6581** [mozilla/mozjpeg#351]
`1.5.90-1982-g`bbb75507

```bash
git clone https://github.com/mozilla/mozjpeg.git code-mozjpeg
cd code-mozjpeg/
git describe
1.5.90-1982-gbbb75507
mkdir build && cd build
cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE ../

(...)
-- PNG reading support enabled (PNG_SUPPORTED = 1)
-- Found ZLIB: /usr/lib/libz.a (found version "1.2.11") 
-- Found PNG: /usr/lib/libpng.a (found suitable version "1.6.37+apng", minimum required is "1.6")
(...)

~/programs/code-mozjpeg/build/cjpeg -quality 85 -sample 1x1 -optimize -outfile foo.jpg foo.png
MozJPEG can't read the image (PNG support is disabled in this build)
```

**Comment by dmak** [comment]
Sorry for tiny offtopic, but I am also trying to compile mozjpeg with PNG support but I get [this error](https://github.com/mozilla/mozjpeg/issues/318#issuecomment-593978735). Should I open a new issue or there is a quickfix for that?

**Comment by afontenot** [comment]
@Beep6581 I'm not sure if you fixed this, but I just encountered the same problem trying to upgrade to the RC. Most likely what is happening is that you have the static build enabled but your system libpng package does not come with the static libraries (libpng.a). If you don't need a static build you will most likely solve your problem just by adding the following to the cmake command:

    -DENABLE_STATIC=FALSE

This does everything I need, personally. :-) 

pinging @kornelski in case this could have a better error message, or some workaround that I'm not thinking of.

**Comment by kornelski** [comment]
Eh, cmake and libpng and a never-ending source of problems :(

In this case the error comes from CMake's own `find_package`:

```cmake
find_package(PNG 1.6 REQUIRED)
```

I guess it could be avoided by:

1. marking PNG as not required
2. checking if the optional find_package succeeded, and emiting a warning if it didn't
3. trying again without the static linking requirement

Anyone wants to wrangle with cmake and make a PR?

**Comment by afontenot** [comment]
Okay, so this is weird, now I'm even more confused. The dynamic build actually claims to support PNG but doesn't. I get a similar output as OP. So using the static build is actually required if you want PNG support.

Here's the thing: the previous release (with the autotools system) builds a working *static* build with PNG support just fine, even though my distribution (Arch Linux) has no libpng.a. I don't know how it's able to do this, I thought a .a was necessary. CMake simply refuses to build at all because a static build was requested, but it can't find the static library.

Anyone know how to work around this issue so that I can at least get a working build with CMake?

**Comment by d3im** [comment]
Have similar problem on Gentoo:
(It's tar.gz release download)
```
$ cmake -G"Unix Makefiles" [...]mozjpeg-4.0.2
...
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib64/libpng.so (found suitable version "1.6.37+apng", minimum required is "1.6") 
-- PNG reading support enabled (PNG_SUPPORTED = 1)
-- Found ZLIB: /usr/lib64/libz.a (found version "1.2.11") 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find PNG (missing: PNG_LIBRARY) (found suitable version
  "1.6.37+apng", minimum required is "1.6")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPNG.cmake:156 (find_package_handle_standard_args)
  CMakeLists.txt:698 (find_package)
...
```

**Comment by kornelski** [comment]
Sorry, this is handled by cmake's build-in function. Clearly cmake does a very poor job here, and I don't know if there's any workaround.

cmake also makes it painful to handle mixed static/dynamic zlib and libpng, and doesn't explain it well when you have one but not the other. 

I can recommend:

```bash
cmake -DPNG_SUPPORTED=NO ..
```

or if you just want the library, use https://lib.rs/crates/mozjpeg which builds it quite reliably, for Rust.

**Comment by afontenot** [comment]
The following currently works for me, I get a dynamic build with PNG support.

    -DENABLE_STATIC=FALSE -DPNG_SUPPORTED=TRUE

IIRC this was broken at one point, but it seems okay now.

**Comment by kornelski** [comment]
I've tried this, which according to random stackoverflow answer is a way to have static/dynamic fallback:

```cmake
    set(CMAKE_FIND_LIBRARY_PREFIXES ${CMAKE_STATIC_LIBRARY_PREFIX})
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_STATIC_LIBRARY_SUFFIX})
    find_package(PNG 1.6 CONFIG QUIET)
    find_package(ZLIB CONFIG QUIET)
    if (NOT PNG_FOUND)
      message("PNG not found")
      set(CMAKE_FIND_LIBRARY_PREFIXES ${CMAKE_SHARED_LIBRARY_PREFIX})
      set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
      find_package(PNG 1.6 REQUIRED)
    endif()
    if (NOT ZLIB_FOUND)
      message("zlib not found")
      set(CMAKE_FIND_LIBRARY_PREFIXES ${CMAKE_SHARED_LIBRARY_PREFIX})
      set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
      find_package(ZLIB REQUIRED)
    endif()
```


but CMake seems to be impossibly broken (this is from macOS + Homebrew):

```text
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/libz.tbd (found version "1.2.11")
-- Found PNG: /usr/local/lib/libpng.dylib (found suitable version "1.6.37", minimum required is "1.6")
-- PNG reading support enabled (PNG_SUPPORTED = 1)
PNG not found
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- Could NOT find PNG (missing: PNG_LIBRARY) (Required is at least version "1.6")
zlib not found
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
```

Whyyyyyy is it found and not found at the same time?

**Comment by AlanSean** [comment]
libpng：
https://packages.msys2.org/base/mingw-w64-libpng
zlib：
https://packages.msys2.org/base/zlib

//Why is that okay
//CMakeLists.txt
```
set(ZLIB_LIBRARY "C:/c++/zlib-1.2.8")
set(ZLIB_INCLUDE_DIR "C:/c++/zlib-1.2.8")
set(PNG_LIBRARY "C:/MinGW")
set(PNG_PNG_INCLUDE_DIR "C:/MinGW")
```//cmd
```
//ok
cmake .. 
```
//Why doesn't that work?
//cmd
```
//error
 cmake -DZLIB_LIBRARY=C:/c++/zlib-1.2.8  -DZLIB_INCLUDE_DIR=C:/c++/zlib-1.2.8 -DPNG_LIBRARY=C:/MinGW -DPNG_PNG_INCLUDE_DIR=C:/MinGW   ..

//error info
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
CMake Error at C:/cmake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PNG (missing: PNG_LIBRARY) (Required is at least version
  "1.6")
```

**Comment by Beep6581** [comment]
```bash
git pull
git describe
v4.0.3-156-gc78b82bb
mkdir build && cd build
cmake -G"Unix Makefiles" -DENABLE_STATIC=FALSE -DPNG_SUPPORTED=TRUE ../

(...)
-- PNG reading support enabled (PNG_SUPPORTED = 1)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib64/libpng.so (found suitable version "1.6.37+apng", minimum required is "1.6") 
-- PNG reading support enabled (PNG_SUPPORTED = 1)
(...)
```

Reading PNG files works correctly now. I will close the issue.
