### ISSUE TITLE
Problem with non-ASCII filename

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla/mozjpeg#354]
File with english name compressed without problem, but if I rename same file and use non-english name, e.g: `تست.jpg`, the following error shows up:

> jpegtran:  can't open ???.jpeg for reading

What should I do to fix this problem?

**Comment by kornelski** [comment]
My guess is that you're using Windows, and the demo tools were compiled with Visual Studio. Unfortunately, Microsoft's standard library for C doesn't support Unicode in the standard C functions. It requires Windows-specific workarounds, which these tools don't have.

If you're compiling yourself, then use GCC (MinGW) or Clang, and don't use Microsoft's outdated C compiler.

If you're trying to use executables compiled by someone else, try using stdin/stdout (`< file > outfile`), or work around MSVC's problem by renaming the files to ASCII.

**Comment by dehghani-mehdi** [comment]
@kornelski Yes, I'm using Windows. following command works perfectly:

```
type تست.jpg | jpegtran-static > output.jpg
```

But I want to overwrite the original image with optimized version, I tried following commands, but it doesn't work

```
type تست.jpg | jpegtran-static -outfile تست.jpg
type تست.jpg | jpegtran-static > تست.jpg
```

Is there any way to solve this too?

**Comment by zvezdochiot** [comment]
@dehghani-mehdi wants `jpegtran` working not in-line, but through a buffer (that is, in memory). Can provide a `allocator` as an alternative to `stdout`?

**Comment by dofuuz** [comment]
Compiling with MinGW GCC toolchain dose not solve those problems. jpegtran still cannot open filename outside system MBCS codepage.

```
type تست.jpg | jpegtran-static -outfile تست.jpg
```
↑ You are trying to read and write a file at the same time, and it's not allowed. It's not related with non-ASCII filename.

```
type تست.jpg | jpegtran-static > output.jpg
move /y output.jpg تست.jpg
```
↑ You should split it to two steps.

**Comment by dehghani-mehdi** [comment]
@dofuuz I can live with that. thank you!
