### ISSUE TITLE
[Usage] Existing JPEG

### ISSUE THREAD

**Issue by strarsis** [mozilla/mozjpeg#356]
Let's say a library generated JPEG files that are already compressed, e.g. 94%. Can I still run these through `mozjpeg` for optimization? Would `mozjpeg` with 100% quality mean that the JPEG quality of 94% would be kept? Will using `mozjpeg` directly during the output as JPEG (some libraries can be built to use `mozjpeg` instead of e.g. `libjpeg-turbo` (as the [`sharp`](https://github.com/lovell/sharp) library does) yield a higher image quality for the same optimizations?

**Comment by zvezdochiot** [comment]
@strarsis say:
>Can I still run these through mozjpeg for optimization?

https://github.com/danielgtaylor/jpeg-archive : jpeg-recompress

> Dependencies: mozjpeg

**Comment by strarsis** [comment]
@zvezdochiot: From the links you posted I think to understand that `mozjpeg` can indeed be used on existing JPEGs and that it wouldn't introduce more artifacts than using it as library during output, e.g. when outputting a JPEG file using the `sharp` library.

**Comment by zvezdochiot** [comment]
@strarsis say:
>it wouldn't introduce more artifacts than using it as library during output

No. The output of `mozjpeg` is not much different from `libjpeg` (is it any different?). Mozjpeg is aimed specifically at coding, and decoding is standard. If you need otherwise, see:
* https://github.com/victorvde/jpeg2png
* https://github.com/ilyakurdyukov/jpeg-quantsmooth

**Comment by strarsis** [comment]
@zvezdochiot: So I want to use mozjpeg for improving the compression (or quality-compression-ratio) of JPEGs. Currently I first use the `sharp` to output "normal" JPEGs with 100% quality, then I use `mozjpeg` from `imagemin-mozjpeg` to compress it to e.g. 90% quality.

**Comment by zvezdochiot** [comment]
@strarsis say:
>use mozjpeg from imagemin-mozjpeg to compress it to e.g. 90% quality.

See also:
* https://github.com/technopagan/adept-jpg-compressor
* https://github.com/BASH-Auto-Tools/bash-jpegmin
* https://github.com/danielgtaylor/jpeg-archive

**Comment by strarsis** [comment]
@zvezdochiot: https://github.com/imagemin/imagemin-guetzli#notes
> Guetzli is designed to work on high quality images (e.g. that haven't been already compressed with other JPEG encoders). While it will work on other images too, results will be poorer. You can try compressing an enclosed sample high quality image.
But this means a raw image buffer or lossless image (e.g. PNG) should be preferred as source instead a JPEG file?

**Comment by kornelski** [comment]
You can use `jpegtran` from MozJPEG on already-compressed JPEGs and this will losslessly improve compression *a bit*.

If you want to take full advantage of MozJPEG's compression, you have to use it to convert uncompressed original (e.g. PNG) to JPEG.

Converting high-quality JPEG to lower-quality JPEG is reasonable, but not as optimal as converting uncompressed originals.

Converting low-quality JPEG to JPEG doesn't make sense.
