### ISSUE TITLE
Install 3.3.1 on CentOS 7

### ISSUE THREAD

**Issue by ghnp5** [mozilla/mozjpeg#359]
I used to be able to install MozJPEG without a problem, but the upgrade to 3.3.1 is giving me a headache.

The instructions in BUILDING are very confusing. All I want is simple steps how to install this for production, that's all.

Isn't there a way to install this through "yum" ?

Anyway, I was trying to build MozJPEG, but I'm getting the following error:

```
$ yum install -y autoconf automake libtool nasm make cmake
$ cd /usr/local/src
$ wget https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz
$ tar -xvzf v3.3.1.tar.gz
$ cd mozjpeg-3.3.1
$ mkdir build && cd build
$ cmake -G"Unix Makefiles" ../
```

> [root@server build]# cmake -G"Unix Makefiles" ../
> -- The C compiler identification is GNU 4.8.5
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> CMake Error at CMakeLists.txt:15 (message):
>   Platform not supported by this build system.  Use autotools instead.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeOutput.log".

> [root@server build]# cat /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeOutput.log
> The system is: Linux - 3.10.0-1127.el7.x86_64 - x86_64
> Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
> Compiler: /usr/bin/cc
> Build flags:
> Id flags:
> 
> The output was:
> 0
> 
> 
> Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
> 
> The C compiler identification is GNU, found in "/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/2.8.12.2/CompilerIdC/a.out"
> 
> Determining if the C compiler works passed with the following output:
> Change Dir: /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:/usr/bin/gmake "cmTryCompileExec3432362171/fast"
> /usr/bin/gmake -f CMakeFiles/cmTryCompileExec3432362171.dir/build.make CMakeFiles/cmTryCompileExec3432362171.dir/build
> gmake[1]: Entering directory `/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp'
> /usr/bin/cmake -E cmake_progress_report /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp/CMakeFiles 1
> Building C object CMakeFiles/cmTryCompileExec3432362171.dir/testCCompiler.c.o
> /usr/bin/cc    -o CMakeFiles/cmTryCompileExec3432362171.dir/testCCompiler.c.o   -c /usr/local/src/mozjpeg-3.3.1/build/CMakeFil
> Linking C executable cmTryCompileExec3432362171
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3432362171.dir/link.txt --verbose=1
> /usr/bin/cc       CMakeFiles/cmTryCompileExec3432362171.dir/testCCompiler.c.o  -o cmTryCompileExec3432362171 -rdynamic
> gmake[1]: Leaving directory `/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp'
> 
> 
> Detecting C compiler ABI info compiled with the following output:
> Change Dir: /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:/usr/bin/gmake "cmTryCompileExec4244039431/fast"
> /usr/bin/gmake -f CMakeFiles/cmTryCompileExec4244039431.dir/build.make CMakeFiles/cmTryCompileExec4244039431.dir/build
> gmake[1]: Entering directory `/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp'
> /usr/bin/cmake -E cmake_progress_report /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp/CMakeFiles 1
> Building C object CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o
> /usr/bin/cc    -o CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake/Modules/CMakeCCompiler
> Linking C executable cmTryCompileExec4244039431
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec4244039431.dir/link.txt --verbose=1
> /usr/bin/cc     -v CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec4244039431 -rdynamic
> Using built-in specs.
> COLLECT_GCC=/usr/bin/cc
> COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
> Target: x86_64-redhat-linux
> Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.restem-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linkni-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog--with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
> Thread model: posix
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
> COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-
> LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:
> COLLECT_GCC_OPTIONS='-v' '-o' 'cmTryCompileExec4244039431' '-rdynamic' '-mtune=generic' '-march=x86-64'
>  /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 edhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_645/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. CMakeFiles/cmTryCompc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/cr
> gmake[1]: Leaving directory `/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp'
> 
> 
> Parsed C implicit link information from above output:
>   link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
>   ignore line: [Change Dir: /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp]
>   ignore line: []
>   ignore line: [Run Build Command:/usr/bin/gmake "cmTryCompileExec4244039431/fast"]
>   ignore line: [/usr/bin/gmake -f CMakeFiles/cmTryCompileExec4244039431.dir/build.make CMakeFiles/cmTryCompileExec4244039431.d
>   ignore line: [gmake[1]: Entering directory `/usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp']
>   ignore line: [/usr/bin/cmake -E cmake_progress_report /usr/local/src/mozjpeg-3.3.1/build/CMakeFiles/CMakeTmp/CMakeFiles 1]
>   ignore line: [Building C object CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o]
>   ignore line: [/usr/bin/cc    -o CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake/Module
>   ignore line: [Linking C executable cmTryCompileExec4244039431]
>   ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec4244039431.dir/link.txt --verbose=1]
>   ignore line: [/usr/bin/cc     -v CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec4244039
>   ignore line: [Using built-in specs.]
>   ignore line: [COLLECT_GCC=/usr/bin/cc]
>   ignore line: [COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper]
>   ignore line: [Target: x86_64-redhat-linux]
>   ignore line: [Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=htelease --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-buil --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-instdirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux]
>   ignore line: [Thread model: posix]
>   ignore line: [gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ]
>   ignore line: [COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib
>   ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/
>   ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTryCompileExec4244039431' '-rdynamic' '-mtune=generic' '-march=x86-64']
>   link line: [ /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu b/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/hat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. CMakeFas-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../
>     arg [/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2] ==> ignore
>     arg [--build-id] ==> ignore
>     arg [--no-add-needed] ==> ignore
>     arg [--eh-frame-hdr] ==> ignore
>     arg [--hash-style=gnu] ==> ignore
>     arg [-m] ==> ignore
>     arg [elf_x86_64] ==> ignore
>     arg [-export-dynamic] ==> ignore
>     arg [-dynamic-linker] ==> ignore
>     arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
>     arg [-o] ==> ignore
>     arg [cmTryCompileExec4244039431] ==> ignore
>     arg [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o] ==> ignore
>     arg [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o] ==> ignore
>     arg [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o] ==> ignore
>     arg [-L/usr/lib/gcc/x86_64-redhat-linux/4.8.5] ==> dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5]
>     arg [-L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64] ==> dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../
>     arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
>     arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
>     arg [-L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../..] ==> dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../..]
>     arg [CMakeFiles/cmTryCompileExec4244039431.dir/CMakeCCompilerABI.c.o] ==> ignore
>     arg [-lgcc] ==> lib [gcc]
>     arg [--as-needed] ==> ignore
>     arg [-lgcc_s] ==> lib [gcc_s]
>     arg [--no-as-needed] ==> ignore
>     arg [-lc] ==> lib [c]
>     arg [-lgcc] ==> lib [gcc]
>     arg [--as-needed] ==> ignore
>     arg [-lgcc_s] ==> lib [gcc_s]
>     arg [--no-as-needed] ==> ignore
>     arg [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o] ==> ignore
>     arg [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o] ==> ignore
>   remove lib [gcc]
>   remove lib [gcc_s]
>   remove lib [gcc]
>   remove lib [gcc_s]
>   collapse library dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5] ==> [/usr/lib/gcc/x86_64-redhat-linux/4.8.5]
>   collapse library dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64] ==> [/usr/lib64]
>   collapse library dir [/lib/../lib64] ==> [/lib64]
>   collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
>   collapse library dir [/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../..] ==> [/usr/lib]
>   implicit libs: [c]
>   implicit dirs: [/usr/lib/gcc/x86_64-redhat-linux/4.8.5;/usr/lib64;/lib64;/usr/lib]
>   implicit fwks: []
> 
> 
>

**Comment by ghnp5** [comment]
Seems I figured out a way to compile this...
I really recommend making your BUILDING instructions easier to read and follow.

This worked for me:

```
$ yum install autoconf automake libtool nasm make cmake
$ cd /usr/local/src
$ wget https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz
$ tar -xvzf v3.3.1.tar.gz
$ cd mozjpeg-3.3.1
$ autoreconf -i
$ ./configure && make
$ make install
```

**Comment by kornelski** [comment]
This is out of date now. libjpeg-turbo has removed configure && make, and uses cmake now.
