### ISSUE TITLE
A lot of effort to figure out statically linking with CMake

### ISSUE THREAD

**Issue by a-vrma** [mozilla/mozjpeg#369]
I am trying to make a fully static build of the binaries (as in [libc](https://musl.libc.org/) is linked statically, not just libpng and libz). I was finally able to get it to work with the following Dockerfile:
```
FROM voidlinux/voidlinux-musl:latest
RUN xbps-install -Su -y \
    base-devel nasm libpng-devel cmake ninja git ncurses-base
RUN useradd -m builder
WORKDIR /home/builder
USER builder
ENV CFLAGS -O3 -march=native -static -static-libgcc -static-libstdc++
# ENV LDFLAGS -flto
RUN git clone 'https://github.com/mozilla/mozjpeg.git' \
    && cd mozjpeg \
    && cmake -S . -B build -G Ninja -D ENABLE_SHARED=0 -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D CMAKE_EXE_LINKER_FLAGS=-static -D CMAKE_FIND_LIBRARY_SUFFIXES=.a \
    -D CMAKE_LINK_SEARCH_END_STATIC=1 -D CMAKE_LINK_SEARCH_START_STATIC=1 
```
The important part is the last RUN command, where there are a lot of defines. After all this I am able to build a fully static {cjpeg,jpegtran,djpeg} binary, but the linking command isn't actually perfect. The command to link cjpeg is
```
: && /usr/sbin/cc -O3 -march=native -static -static-libgcc -static-libstdc++ -O3 -DNDEBUG -static   -rdynamic CMakeFiles/cjpeg-static.dir/cjpeg.c.o CMakeFiles/cjpeg-static.dir/cdjpeg.c.o CMakeFiles/cjpeg-static.dir/rdgif.c.o CMakeFiles/cjpeg-static.dir/rdppm.c.o CMakeFiles/cjpeg-static.dir/rdjpeg.c.o CMakeFiles/cjpeg-static.dir/rdswitch.c.o CMakeFiles/cjpeg-static.dir/rdbmp.c.o CMakeFiles/cjpeg-static.dir/rdtarga.c.o CMakeFiles/cjpeg-static.dir/rdpng.c.o -o cjpeg-static  libjpeg.a  -lm  -lpng  -lz && :
```
Notice that there is still a wayward -rdynamic in there. I'm not sure if that negatively affects the binaries, though. If anyone knows what obscure incantations I should do to get rid of that parameter, please help.

My actual issue is that I think this should be somewhat easier to do. It was significantly easier back when you were using GNU Autotools. Maybe you can add my Dockerfile to the repository or wiki?

**Comment by a-vrma** [comment]
The solution is maybe in the CMakeLists.txt in `if(ENABLE_STATIC)` we can reset `CMAKE_SHARED_LIBRARY_LINK_C_FLAGS` to the empty string. That's similar to what [this library is doing](https://github.com/commonmark/cmark/blob/master/CMakeLists.txt).

Setting that variable to an empty string from the command line doesn't seem to work.

**Comment by kornelski** [comment]
Yes, `cmake` is a pain. It's inherited from the libjpeg-turbo project, so I'd rather not change it. 

Personally I use Rust's Cargo to build MozJPEG: https://lib.rs/mozjpeg-sys (this doesn't include the demo tools like `cjpeg`/`djpeg`, but I recommend using the library API).

**Comment by a-vrma** [comment]
> Yes, `cmake` is a pain. It's inherited from the libjpeg-turbo project, so I'd rather not change it.

That's fair

> Personally I use Rust's Cargo to build MozJPEG: https://lib.rs/mozjpeg-sys (this doesn't include the demo tools like cjpeg/djpeg, but I recommend using the library API).

Everyone uses the demo tools though :^) .
In any case, this is the Dockerfile I ended up with:

```
FROM voidlinux/voidlinux-musl:latest
RUN xbps-install -Su -y \
    base-devel nasm libpng-devel cmake ninja git
RUN useradd -m builder
WORKDIR /home/builder
USER builder
ENV CFLAGS -O3 -march=native -static -static-libgcc -static-libstdc++ -flto
ENV LDFLAGS -flto -static
RUN git clone 'https://github.com/mozilla/mozjpeg.git' \
    && cd mozjpeg \
    # This unsets CMAKE_SHARED_LIBRARY_LINK_C_FLAGS inside CMakeLists.txt because it won't work from the CLI.
    && perl -ni -e 'print; /set\(LIBJPEG_TURBO_V/ && print "set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)"' CMakeLists.txt \
    && cmake -S . -B build -G Ninja -D ENABLE_SHARED=0 -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D CMAKE_EXE_LINKER_FLAGS="$LDFLAGS" -D CMAKE_FIND_LIBRARY_SUFFIXES=.a \
    -D CMAKE_LINK_SEARCH_END_STATIC=1 -D CMAKE_LINK_SEARCH_START_STATIC=1 \
    && cmake --build build \
    && strip -s build/cjpeg-static build/djpeg-static build/jpegtran-static
```

**Comment by kornelski** [comment]
Thanks for sharing.
