### ISSUE TITLE
JPG not rotated losslessly with -perfect

### ISSUE THREAD

**Issue by krishty** [mozilla/mozjpeg#370]
A JPG of mine is not rotated losslessly even with `-perfect` specified.

1. I’m using mozjpegtran 3.3.1 on Windows.
2. No output indicates that the file is damaged, so I hope it’s no duplicate of #224 .
3. The images come out different both when opened with GIMP as well as with MS Paint, so I assume it’s no decoder issue either.
4. I used an old build from 2015 I had laying around and got the same result.

Source image:
![test](https://user-images.githubusercontent.com/51880096/91837967-0e9c9080-ec4d-11ea-93b5-c4fd84fa473a.jpg)

Command line:
```jpegtran.exe -copy all -rotate 270 -perfect -debug test.jpg > test_rotated.jpg```

Output:
![test_rotated](https://user-images.githubusercontent.com/51880096/91837974-10feea80-ec4d-11ea-918f-20535a7e5531.jpg)

The rotation was not lossless; lots of pixels have changed by ±2/256 in multiple color channels. This is the diff (contrast enhanced) I created via GIMP:
![diff](https://user-images.githubusercontent.com/51880096/91837994-1825f880-ec4d-11ea-9dab-76d039b0c48b.png)

The output does not indicate anything fishy:
```
mozjpeg version 3.3.1 (build 20190610)
Copyright (C) 2009-2017 D. R. Commander
Copyright (C) 2011-2016 Siarhei Siamashka
Copyright (C) 2015-2016 Matthieu Darbois
Copyright (C) 2015 Google, Inc.
Copyright (C) 2014 Mozilla Corporation
Copyright (C) 2013-2014 MIPS Technologies, Inc.
Copyright (C) 2013 Linaro Limited
Copyright (C) 2009-2011 Nokia Corporation and/or its subsidiary(-ies)
Copyright (C) 2009 Pierre Ossman for Cendio AB
Copyright (C) 1999-2006 MIYASAKA Masaru
Copyright (C) 1991-2016 Thomas G. Lane, Guido Vollbeding

Emulating The Independent JPEG Group's software, version 6b  27-Mar-1998
Start of Image
JFIF APP0 marker: version 1.02, density 1x1  0
Miscellaneous marker 0xe7, length 2076
Define Quantization Table 0  precision 0
Define Quantization Table 1  precision 0
Start Of Frame 0xc2: width=512, height=384, components=3
    Component 1: 2hx1v q=0
    Component 2: 1hx1v q=1
    Component 3: 1hx1v q=1
Define Huffman Table 0x00
Start Of Scan: 1 components
    Component 1: dc=0 ac=0
  Ss=0, Se=0, Ah=0, Al=0
Define Huffman Table 0x01
Start Of Scan: 1 components
    Component 2: dc=1 ac=0
  Ss=0, Se=0, Ah=0, Al=0
Define Huffman Table 0x01
Start Of Scan: 1 components
    Component 3: dc=1 ac=0
  Ss=0, Se=0, Ah=0, Al=0
Define Huffman Table 0x10
Start Of Scan: 1 components
    Component 1: dc=0 ac=0
  Ss=1, Se=5, Ah=0, Al=0
Define Huffman Table 0x10
Start Of Scan: 1 components
    Component 1: dc=0 ac=0
  Ss=6, Se=63, Ah=0, Al=0
Define Huffman Table 0x11
Start Of Scan: 1 components
    Component 2: dc=0 ac=1
  Ss=1, Se=63, Ah=0, Al=0
Define Huffman Table 0x11
Start Of Scan: 1 components
    Component 3: dc=0 ac=1
  Ss=1, Se=63, Ah=0, Al=0
End Of Image

SCAN 0: 0 0 0 0
SCAN 1: 0 0 0 0
SCAN 2: 0 0 0 0
SCAN 0: 1 5 0 0
SCAN 0: 6 63 0 0
SCAN 1: 1 63 0 0
SCAN 2: 1 63 0 0
```

Anyone know what’s happening?

**Comment by kornelski** [comment]
Does this work with libjpeg-turbo

**Comment by krishty** [comment]
Reproduces with libjpeg-turbo 2.0.5 and with the latest mozjpeg (8fb32c0a).

I presume libjpeg-turbo is the better place to report this? If so, should I close the issue here?

**Comment by kornelski** [comment]
Yes, if it affects turbo then file issues there.

**Comment by krishty** [comment]
Thank you for the information. If anyone wants to trace progress, I opened a ticket at https://github.com/libjpeg-turbo/libjpeg-turbo/issues/453 .

**Comment by ValZapod** [comment]
The answer is asymmetric chroma subsampling, indeed as you were told. That is why you must rotate using metadata!
