### ISSUE TITLE
Security Breach #instagram

### ISSUE THREAD

**Issue by adminvns** [mozilla/mozjpeg#378]
# Security Policy Breach

## Allegation:
Security researchers from Checkpoint found the vulnerability with the Instagram app 3rd party library Mozjpeg – an open-source project used by Instagram as its JPEG format image decoder for images uploaded to the service.

The vulnerability is critical it allows attackers to execute code and perform any action they wish n the Instagram app

source -https://gbhackers.com/instagram-hacked-vulnerability/

Is it true?
if yes?patches are released?

**Comment by kornelski** [comment]
That blogspam repost has is incorrect. The vulnerability is specific to Instagram app only, and does not affect MozJPEG.

The [original report](https://research.checkpoint.com/2020/instagram_rce-code-execution-vulnerability-in-instagram-app-for-android-and-ios/) could have been worded better, but it says:

> We found a vulnerability **in the way** that Instagram utilizes Mozjpeg

The vulnerability was in a custom code written by Facebook as part of Instagram app itself. The flaw is in Facebook's integration around MozJPEG, but not in MozJPEG itself.
