### ISSUE TITLE
macOS Universal 2 binary for Apple silicon support?

### ISSUE THREAD

**Issue by andrewcrook** [mozilla/mozjpeg#387]
Please consider this feature request of adding a universal 2 binary with both Intel and Apple Silicon support to the releases.

**Comment by kornelski** [comment]
M1/Apple Silicon is already supported. If you have a compiler capable of building fat binaries, you'll get them automatically.

We don't provide binaries, so there is nothing to be done on your side.

**Comment by lhazell** [comment]
@kornelski Is it possible to manually build mozjpeg?

I am also getting `Unknown system error -86` on Apple Silicon.

I just acquired an M1 machine. If this is a real issue, I would like to help?

------------------------------------------------------------------------------------
**Here's the error I get when I try to install mozjpeg on Apple Silicon:**

`0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node/15.11.0/bin/node',
0 verbose cli   '/opt/homebrew/bin/npm',
0 verbose cli   'install',
0 verbose cli   'mozjpeg'
0 verbose cli ]
1 info using npm@7.6.2
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 0ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/[...]/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/[...]/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 4ms
19 verbose npm-session 3dfece65973d12cd
20 timing npm:load Completed in 10ms
21 timing arborist:ctor Completed in 0ms
22 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
23 timing idealTree:init Completed in 267ms
24 timing idealTree:userRequests Completed in 2ms
25 silly idealTree buildDeps
26 silly fetch manifest mozjpeg@*
27 http fetch GET 304 https://registry.npmjs.org/mozjpeg 506ms (from cache)
28 silly placeDep ROOT mozjpeg@7.0.0 OK for: bootstrap-gulp-starter@1.0.0 want: *
29 timing idealTree:#root Completed in 512ms
30 timing idealTree:node_modules/mozjpeg Completed in 0ms
31 timing idealTree:buildDeps Completed in 512ms
32 timing idealTree:fixDepFlags Completed in 4ms
33 timing idealTree Completed in 793ms
34 timing reify:loadTrees Completed in 795ms
35 timing reify:diffTrees Completed in 13ms
36 silly reify moves {}
37 timing reify:retireShallow Completed in 0ms
38 timing reify:createSparse Completed in 0ms
39 timing reify:loadBundles Completed in 0ms
40 timing reifyNode:node_modules/imagemin-optipng Completed in 25ms
41 timing reifyNode:node_modules/mozjpeg Completed in 29ms
42 timing reifyNode:node_modules/optipng-bin Completed in 30ms
43 timing reify:unpack Completed in 30ms
44 timing reify:unretire Completed in 0ms
45 timing build:queue Completed in 1ms
46 timing build:link:node_modules/mozjpeg Completed in 0ms
47 timing build:link:node_modules/optipng-bin Completed in 0ms
48 timing build:link Completed in 0ms
49 info run mozjpeg@7.0.0 postinstall node_modules/mozjpeg node lib/install.js
50 info run optipng-bin@6.0.0 postinstall node_modules/optipng-bin node lib/install.js
51 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 511ms
52 timing auditReport:getReport Completed in 513ms
53 timing metavuln:cache:get:security-advisory:marked:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 25ms
54 timing metavuln:cache:get:security-advisory:clean-css:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 26ms
55 timing metavuln:cache:get:security-advisory:minimist:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 24ms
56 timing metavuln:cache:get:security-advisory:braces:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 27ms
57 timing metavuln:cache:get:security-advisory:axios:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 28ms
58 http fetch GET 304 https://registry.npmjs.org/marked 185ms (from cache)
59 timing metavuln:packument:marked Completed in 185ms
60 timing metavuln:load:security-advisory:marked:1623 Completed in 1ms
61 timing metavuln:calculate:security-advisory:marked:1623 Completed in 186ms
62 http fetch GET 304 https://registry.npmjs.org/minimist 284ms (from cache)
63 timing metavuln:packument:minimist Completed in 285ms
64 timing metavuln:load:security-advisory:minimist:1179 Completed in 0ms
65 timing metavuln:calculate:security-advisory:minimist:1179 Completed in 285ms
66 http fetch GET 304 https://registry.npmjs.org/braces 291ms (from cache)
67 timing metavuln:packument:braces Completed in 291ms
68 timing metavuln:load:security-advisory:braces:786 Completed in 0ms
69 timing metavuln:calculate:security-advisory:braces:786 Completed in 292ms
70 http fetch GET 304 https://registry.npmjs.org/axios 293ms (from cache)
71 timing metavuln:packument:axios Completed in 293ms
72 timing metavuln:load:security-advisory:axios:1594 Completed in 1ms
73 timing metavuln:calculate:security-advisory:axios:1594 Completed in 295ms
74 http fetch GET 304 https://registry.npmjs.org/clean-css 319ms (from cache)
75 timing metavuln:packument:clean-css Completed in 321ms
76 timing metavuln:load:security-advisory:clean-css:785 Completed in 1ms
77 timing metavuln:calculate:security-advisory:clean-css:785 Completed in 322ms
78 timing metavuln:cache:get:security-advisory:access-sniff:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 2ms
79 http fetch GET 304 https://registry.npmjs.org/access-sniff 110ms (from cache)
80 timing metavuln:packument:access-sniff Completed in 110ms
81 timing metavuln:load:security-advisory:access-sniff:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 0ms
82 timing metavuln:calculate:security-advisory:access-sniff:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 110ms
83 timing metavuln:cache:get:security-advisory:micromatch:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 1ms
84 http fetch GET 304 https://registry.npmjs.org/micromatch 67ms (from cache)
85 timing metavuln:packument:micromatch Completed in 67ms
86 timing metavuln:load:security-advisory:micromatch:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 0ms
87 timing metavuln:calculate:security-advisory:micromatch:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 67ms
88 timing metavuln:cache:get:security-advisory:gulp-cssmin:zpp9vwWjftjJcyOnbmEVF6q9ZhBNaAXmBoJwFb51nH90PG4wsxEpNTZ160beH36Pp+GGcsrcxYNu90QYVQ2g1A== Completed in 4ms
89 http fetch GET 304 https://registry.npmjs.org/gulp-cssmin 75ms (from cache)
90 timing metavuln:packument:gulp-cssmin Completed in 75ms
91 timing metavuln:load:security-advisory:gulp-cssmin:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 0ms
92 timing metavuln:calculate:security-advisory:gulp-cssmin:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 76ms
93 timing metavuln:cache:get:security-advisory:panini:jpmuyLwykZhmRjrpb0hOl3sis/eRonHtJQg1GEYmujvk4L/Br508pDMe+hdwzi9uT5b3Wj5lRkz72xAnj2S6wA== Completed in 1ms
94 http fetch GET 304 https://registry.npmjs.org/panini 332ms (from cache)
95 timing metavuln:packument:panini Completed in 333ms
96 timing metavuln:load:security-advisory:panini:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 0ms
97 timing metavuln:calculate:security-advisory:panini:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 333ms
98 timing metavuln:cache:get:security-advisory:csscomb:P6FHjBfa9ieh71aVyT+n7gktibDk6+5oc/BndPOeBxUZW8ccLf9q0Z0DAqL07WKPCI0yCqIM5LBk+i90DiN57g== Completed in 15ms
99 timing metavuln:cache:get:security-advisory:gonzales-pe:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 16ms
100 timing metavuln:cache:get:security-advisory:gonzales-pe-sl:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 16ms
101 timing metavuln:cache:get:security-advisory:gulp-util:kdVUBCpcnd5mKKx0BdoPIHqRdxVJR5/iEPe+l1v3nPmDXN4eDiye9gp2ro2prgaXhfdKx9ckLUpleh8VkF2zCw== Completed in 15ms
102 timing metavuln:cache:get:security-advisory:blocking-proxy:esfR0TLdsWb4wf/9LDLcjtkSUllycRtQTFo2mGXWmlscDFJfZmFY7iQobbSYjQxlrGP3jfyc6IQo7BTqULOnoQ== Completed in 15ms
103 timing metavuln:cache:get:security-advisory:rc:5CaxaUsjK4hm5YGxZdsHBERbkhg2ayjB1F7KkltT/spva+03R7PxDydCg1iRXZrD/kq/c4RheFJZFfjh0Cjw0w== Completed in 14ms
104 timing metavuln:cache:get:security-advisory:webdriver-manager:HQCnPZRKdILckzoAQd3V1wbzPjI/Nfk7ytZNBwDDoZ+E0tGJxD9GGk/6Juss2R+0w15bnYsjFfa3hshtBnGxRA== Completed in 14ms
105 timing metavuln:cache:get:security-advisory:meow:77nL6GjRTgs6PsZG9tit194Ki9THziHyRIcjBSdroet8DrYHx5VMZREYspMrKEYQf7FYG0Oh5nw/4kAKIyk2eg== Completed in 15ms
106 http fetch GET 304 https://registry.npmjs.org/csscomb 63ms (from cache)
107 timing metavuln:packument:csscomb Completed in 63ms
108 timing metavuln:load:security-advisory:csscomb:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
109 timing metavuln:calculate:security-advisory:csscomb:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 63ms
110 http fetch GET 304 https://registry.npmjs.org/gonzales-pe-sl 64ms (from cache)
111 timing metavuln:packument:gonzales-pe-sl Completed in 64ms
112 timing metavuln:load:security-advisory:gonzales-pe-sl:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
113 timing metavuln:calculate:security-advisory:gonzales-pe-sl:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 64ms
114 http fetch GET 304 https://registry.npmjs.org/gonzales-pe 68ms (from cache)
115 timing metavuln:packument:gonzales-pe Completed in 69ms
116 timing metavuln:load:security-advisory:gonzales-pe:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
117 timing metavuln:calculate:security-advisory:gonzales-pe:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 69ms
118 http fetch GET 304 https://registry.npmjs.org/blocking-proxy 81ms (from cache)
119 timing metavuln:packument:blocking-proxy Completed in 81ms
120 timing metavuln:load:security-advisory:blocking-proxy:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
121 timing metavuln:calculate:security-advisory:blocking-proxy:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 81ms
122 http fetch GET 304 https://registry.npmjs.org/webdriver-manager 83ms (from cache)
123 timing metavuln:packument:webdriver-manager Completed in 84ms
124 timing metavuln:load:security-advisory:webdriver-manager:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
125 timing metavuln:calculate:security-advisory:webdriver-manager:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 84ms
126 http fetch GET 304 https://registry.npmjs.org/rc 155ms (from cache)
127 timing metavuln:packument:rc Completed in 156ms
128 timing metavuln:load:security-advisory:rc:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
129 timing metavuln:calculate:security-advisory:rc:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 156ms
130 http fetch GET 304 https://registry.npmjs.org/meow 167ms (from cache)
131 timing metavuln:packument:meow Completed in 167ms
132 timing metavuln:load:security-advisory:meow:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
133 timing metavuln:calculate:security-advisory:meow:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 167ms
134 http fetch GET 304 https://registry.npmjs.org/gulp-util 170ms (from cache)
135 timing metavuln:packument:gulp-util Completed in 171ms
136 timing metavuln:load:security-advisory:gulp-util:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
137 timing metavuln:calculate:security-advisory:gulp-util:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 171ms
138 timing metavuln:cache:get:security-advisory:gulp-accessibility:5MYC3Mc3DKOrPqu+CDR/mG1Qrq7QwrsrN2B6ReJNRDTV2bhKJEL44FNwnkbqXlAHhGA83WkK61sUDLVZjAxqKA== Completed in 1ms
139 http fetch GET 304 https://registry.npmjs.org/gulp-accessibility 350ms (from cache)
140 timing metavuln:packument:gulp-accessibility Completed in 351ms
141 timing metavuln:load:security-advisory:gulp-accessibility:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 0ms
142 timing metavuln:calculate:security-advisory:gulp-accessibility:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 351ms
143 timing metavuln:cache:get:security-advisory:glob-stream:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 7ms
144 http fetch GET 304 https://registry.npmjs.org/glob-stream 65ms (from cache)
145 timing metavuln:packument:glob-stream Completed in 66ms
146 timing metavuln:load:security-advisory:glob-stream:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 0ms
147 timing metavuln:calculate:security-advisory:glob-stream:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 66ms
148 timing metavuln:cache:get:security-advisory:sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 3ms
149 http fetch GET 304 https://registry.npmjs.org/sass-lint 64ms (from cache)
150 timing metavuln:packument:sass-lint Completed in 64ms
151 timing metavuln:load:security-advisory:sass-lint:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 0ms
152 timing metavuln:calculate:security-advisory:sass-lint:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 64ms
153 timing metavuln:cache:get:security-advisory:csscomb:hM3iqlHtzEtu9+SBnA2iFmq3enyNJojQ5xQTMoM4dRvqxRECdLJ51ikFYAdTNJO95TlDIfXoFsv9FiaDxMmV0A== Completed in 2ms
154 timing metavuln:load:security-advisory:csscomb:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 0ms
155 timing metavuln:calculate:security-advisory:csscomb:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 2ms
156 timing metavuln:cache:get:security-advisory:vinyl-fs:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 2ms
157 http fetch GET 304 https://registry.npmjs.org/vinyl-fs 83ms (from cache)
158 timing metavuln:packument:vinyl-fs Completed in 85ms
159 timing metavuln:load:security-advisory:vinyl-fs:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 0ms
160 timing metavuln:calculate:security-advisory:vinyl-fs:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 85ms
161 timing metavuln:cache:get:security-advisory:gulp-sass-lint:YqZipIDki12CVk3y20cm7SOD6LTOQrs9C1uyqOdAmVbS92VZetkrVeg91z2rgYKjYClFdE9lppXcV2yefEmVaw== Completed in 2ms
162 http fetch GET 304 https://registry.npmjs.org/gulp-sass-lint 458ms (from cache)
163 timing metavuln:packument:gulp-sass-lint Completed in 458ms
164 timing metavuln:load:security-advisory:gulp-sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 0ms
165 timing metavuln:calculate:security-advisory:gulp-sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 458ms
166 timing metavuln:cache:get:security-advisory:gulp-gh-pages:IQCrdKW6rGkQjfbiFamZzhQ8CHYnPGw71Xi/VbU/qfoUg2CX9e4ZihkZ6SbSXzC20cGWX7aEMOFElQ1mxlGyBg== Completed in 2ms
167 http fetch GET 304 https://registry.npmjs.org/gulp-gh-pages 485ms (from cache)
168 timing metavuln:packument:gulp-gh-pages Completed in 485ms
169 timing metavuln:load:security-advisory:gulp-gh-pages:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 0ms
170 timing metavuln:calculate:security-advisory:gulp-gh-pages:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 485ms
171 timing auditReport:init Completed in 2611ms
172 timing reify:audit Completed in 3124ms
173 info run optipng-bin@6.0.0 postinstall { code: 1, signal: null }
174 verbose reify failed optional dependency /[...]/node_modules/optipng-bin
175 silly reify mark deleted [
175 silly reify   '/[...]/node_modules/optipng-bin',
175 silly reify   '/[...]/node_modules/.bin/optipng'
175 silly reify ]
176 verbose reify failed optional dependency /[...]/node_modules/imagemin-optipng
177 silly reify mark deleted [
177 silly reify   '/[...]/node_modules/imagemin-optipng'
177 silly reify ]
178 timing build:run:postinstall:node_modules/optipng-bin Completed in 4347ms
179 info run mozjpeg@7.0.0 postinstall { code: 1, signal: null }
180 timing reify:rollback:createSparse Completed in 4ms
181 timing reify:rollback:retireShallow Completed in 0ms
182 timing command:install Completed in 9324ms
183 verbose stack Error: command failed
183 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
183 verbose stack     at ChildProcess.emit (node:events:378:20)
183 verbose stack     at maybeClose (node:internal/child_process:1067:16)
183 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
184 verbose pkgid mozjpeg@7.0.0
185 verbose cwd /[...]
186 verbose Darwin 20.3.0
187 verbose argv "/opt/homebrew/Cellar/node/15.11.0/bin/node" "/opt/homebrew/bin/npm" "install" "mozjpeg"
188 verbose node v15.11.0
189 verbose npm  v7.6.2
190 error code 1
191 error path /[...]/node_modules/mozjpeg
192 error command failed
193 error command sh -c node lib/install.js
194 error ⚠ spawn Unknown system error -86
194 error   ⚠ mozjpeg pre-build test failed
194 error   ℹ compiling from source
194 error   ✖ Error: Command failed: /bin/sh -c ./configure --enable-static --disable-shared --disable-dependency-tracking --with-jpeg8 libpng_LIBS='/usr/local/lib/libpng16.a -lz' --enable-static --prefix="/[...]/node_modules/mozjpeg/vendor" --bindir="/[...]/node_modules/mozjpeg/vendor" --libdir="/[...]/node_modules/mozjpeg/vendor"
194 error ./configure: line 13595: PKG_PROG_PKG_CONFIG: command not found
194 error ./configure: line 13774: syntax error near unexpected token `libpng,'
194 error ./configure: line 13774: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'
194 error
194 error checking for a BSD-compatible install... /usr/bin/install -c
194 error checking whether build environment is sane... yes
194 error checking for a thread-safe mkdir -p... ./install-sh -c -d
194 error checking for gawk... no
194 error checking for mawk... no
194 error checking for nawk... no
194 error checking for awk... awk
194 error checking whether make sets $(MAKE)... yes
194 error checking whether make supports nested variables... yes
194 error checking whether make supports nested variables... (cached) yes
194 error checking whether make supports the include directive... yes (GNU style)
194 error checking for gcc... gcc
194 error checking whether the C compiler works... yes
194 error checking for C compiler default output file name... a.out
194 error checking for suffix of executables...
194 error checking whether we are cross compiling... no
194 error checking for suffix of object files... o
194 error checking whether we are using the GNU C compiler... yes
194 error checking whether gcc accepts -g... yes
194 error checking for gcc option to accept ISO C89... none needed
194 error checking whether gcc understands -c and -o together... yes
194 error checking dependency style of gcc... none
194 error checking how to run the C preprocessor... gcc -E
194 error checking for gcc... (cached) gcc
194 error checking whether we are using the GNU C compiler... (cached) yes
194 error checking whether gcc accepts -g... (cached) yes
194 error checking for gcc option to accept ISO C89... (cached) none needed
194 error checking whether gcc understands -c and -o together... (cached) yes
194 error checking dependency style of gcc... (cached) none
194 error checking for ar... ar
194 error checking the archiver (ar) interface... ar
194 error checking dependency style of gcc... none
194 error checking the archiver (ar) interface... (cached) ar
194 error checking build system type... aarch64-apple-darwin20.3.0
194 error checking host system type... aarch64-apple-darwin20.3.0
194 error checking how to print strings... printf
194 error checking for a sed that does not truncate output... /usr/bin/sed
194 error checking for grep that handles long lines and -e... /usr/bin/grep
194 error checking for egrep... /usr/bin/grep -E
194 error checking for fgrep... /usr/bin/grep -F
194 error checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
194 error checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
194 error checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
194 error checking the name lister (/usr/bin/nm -B) interface... BSD nm
194 error checking whether ln -s works... yes
194 error checking the maximum length of command line arguments... 786432
194 error checking how to convert aarch64-apple-darwin20.3.0 file names to aarch64-apple-darwin20.3.0 format... func_convert_file_noop
194 error checking how to convert aarch64-apple-darwin20.3.0 file names to toolchain format... func_convert_file_noop
194 error checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
194 error checking for objdump... objdump
194 error checking how to recognize dependent libraries... pass_all
194 error checking for dlltool... no
194 error checking how to associate runtime and link libraries... printf %s\n
194 error checking for archiver @FILE support... no
194 error checking for strip... strip
194 error checking for ranlib... ranlib
194 error checking command to parse /usr/bin/nm -B output from gcc object... ok
194 error checking for sysroot... no
194 error checking for a working dd... /bin/dd
194 error checking how to truncate binary pipes... /bin/dd bs=4096 count=1
194 error checking for mt... no
194 error checking if : is a manifest tool... no
194 error checking for dsymutil... dsymutil
194 error checking for nmedit... nmedit
194 error checking for lipo... lipo
194 error checking for otool... otool
194 error checking for otool64... no
194 error checking for -single_module linker flag... yes
194 error checking for -exported_symbols_list linker flag... yes
194 error checking for -force_load linker flag... yes
194 error checking for ANSI C header files... yes
194 error checking for sys/types.h... yes
194 error checking for sys/stat.h... yes
194 error checking for stdlib.h... yes
194 error checking for string.h... yes
194 error checking for memory.h... yes
194 error checking for strings.h... yes
194 error checking for inttypes.h... yes
194 error checking for stdint.h... yes
194 error checking for unistd.h... yes
194 error checking for dlfcn.h... yes
194 error checking for objdir... .libs
194 error checking if gcc supports -fno-rtti -fno-exceptions... yes
194 error checking for gcc option to produce PIC... -fno-common -DPIC
194 error checking if gcc PIC flag -fno-common -DPIC works... yes
194 error checking if gcc static flag -static works... no
194 error checking if gcc supports -c -o file.o... yes
194 error checking if gcc supports -c -o file.o... (cached) yes
194 error checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
194 error checking dynamic linker characteristics... darwin20.3.0 dyld
194 error checking how to hardcode library paths into programs... immediate
194 error checking whether stripping libraries is possible... yes
194 error checking if libtool supports shared libraries... yes
194 error checking whether to build shared libraries... no
194 error checking whether to build static libraries... yes
194 error checking whether ln -s works... yes
194 error checking size of size_t... 8
194 error checking whether compiler supports pointers to undefined structures... yes
194 error checking whether __SUNPRO_C is declared... no
194 error checking for pow in -lm... yes
194 error
194 error     at /[...]/node_modules/execa/index.js:231:11
194 error     at runMicrotasks (<anonymous>)
194 error     at processTicksAndRejections (node:internal/process/task_queues:94:5)
194 error     at async Promise.all (index 0)
195 verbose exit 1
`

**Comment by kornelski** [comment]
This project does not support Node.js. Please report issues to the author of the node package instead.

**Comment by lhazell** [comment]
Thanks @kornelski. I'll create an issue with the imagemin-mozjpeg package.
