### ISSUE TITLE
Install 4.0.2 on CentOS 7

### ISSUE THREAD

**Issue by ghnp5** [mozilla/mozjpeg#388]
Here I am again, on a similar headache as #359

This time, trying to install 4.0.2...

Why isn't there a package I can simply install using "yum" or similar?
Every time I want to install mozjpeg, I have to be blocked and stuck.

The instructions in BUILDING are very confusing. All I want is simple steps how to install this for production, that's all.

The steps I figured out in #359 no longer work, again, for 4.0.2.

"autoreconf" doesn't work.

I tried to use:

```
yum install -y autoconf automake libtool nasm make cmake
cd /usr/local/src
wget https://github.com/mozilla/mozjpeg/archive/v4.0.2.tar.gz
tar -xvzf v4.0.2.tar.gz
cd mozjpeg-4.0.2
cmake -G"Unix Makefiles"
```

And I get (in the cmake step):

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) (Required is
>   at least version "1.6")
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake/Modules/FindPNG.cmake:105 (find_package_handle_standard_args)
>   sharedlib/CMakeLists.txt:97 (find_package)

Seriously... how do I build Mozjpeg this time?
Every version it seems to change...

Thank you.

**Comment by kornelski** [comment]
Do you have libpng 1.6 or later?

**Comment by nunoperalta** [comment]
> Do you have libpng 1.6 or later?

Thank you.

I installed it:

```
yum install -y libpng-devel
```

Then got the same error:

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find PNG: Found unsuitable version "1.5.13", but required is at
>   least "1.6" (found /usr/lib64/libpng.so)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake/Modules/FindPNG.cmake:105 (find_package_handle_standard_args)
>   sharedlib/CMakeLists.txt:97 (find_package)

**Comment by ghnp5** [comment]
> Do you have libpng 1.6 or later?

Thank you.

I installed it:

```
yum install -y libpng-devel
```

Then got the same error:

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find PNG: Found unsuitable version "1.5.13", but required is at
>   least "1.6" (found /usr/lib64/libpng.so)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake/Modules/FindPNG.cmake:105 (find_package_handle_standard_args)
>   sharedlib/CMakeLists.txt:97 (find_package)

**Comment by kornelski** [comment]
As it says, you have libpng 1.5.13, but 1.6 or later is required. Your operating system is too old, and lacks a library released in 2014.

**Comment by ghnp5** [comment]
Apologies. I saw the same "Could NOT find PNG", and ignored the rest of the message - automatically assumed it was the same error.

Well, I use CentOS 7, which is still supported. But yes, they have the reputation of keeping outdated software in their repositories.

I see there is other software I use that depends on "libpng" (such as ImageMagick), so I'll park trying to upgrade libpng & mozjpeg for now.

I wonder why is libpng required for mozjpeg, if this program compresses JPG?

Thank you!

**Comment by kornelski** [comment]
It includes a tool that converts PNG to JPEG. If you're not planning to use it, you can disable PNG support.

**Comment by ghnp5** [comment]
Ah ok - thank you!
Is it possible to build without that support? Any flag to include, etc?

**Comment by kornelski** [comment]
That should do it:

```bash
mkdir build
cd build
cmake .. -DPNG_SUPPORTED=NO
make -j8
```

**Comment by ghnp5** [comment]
Thank you. This seems to have worked!
Have a good day.
