### ISSUE TITLE
I want to Sale the mozjpeg.com domain, anyone interested?

### ISSUE THREAD

**Issue by iftkharhussain** [mozilla/mozjpeg#397]
Hi there,

A few years ago I bought a domain (mozjpeg.com) for adding mozjpeg tool and apply adsence on it, due to low traffic it is difficult for me to run this website and I have decided to sell it

the purpose of adding this post here I thought the mozjpeg project has the first right to buy it and add it on this project.

So, please let me know mozjpeg team or anyone wants to buy it. Thanks

**Comment by kornelski** [comment]
No thanks.
