### ISSUE TITLE
Vulnerability in transitive dependency trim-newlines

### ISSUE THREAD

**Issue by karlhorky** [mozilla/mozjpeg#402]
Hi there, thanks for this package!

Transitive dependency chain: `mozjpeg@6.0.0 -> logalot@2.1.0 -> squeak@1.3.0 -> lpad-align@1.1.2 -> meow@3.7.0 -> trim-newlines@^1.0.0`

Vulnerability: https://github.com/advisories/GHSA-7p7h-4mm5-852v

Repro:

```bash
$ mkdir test-pkg
$ cd test-pkg
$ npm init -y
$ npm install mozjpeg
...
$ npm audit
# npm audit report

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix`
node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/meow

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
```

Ref: https://github.com/kevva/logalot/issues/4
Ref: https://github.com/kevva/squeak/issues/4
Ref: https://github.com/kevva/lpad-align/issues/5

**Comment by kornelski** [comment]
This project does not support Node.js. Please report the bug to the person who is repackaging MozJPEG for Node.

**Comment by karlhorky** [comment]
Ah sorry, didn't look closely enough at this repo! 🤦‍♂️

There's an open issue over here in the repo for the `mozjpeg` npm package: https://github.com/imagemin/mozjpeg-bin/issues/63
