### ISSUE TITLE
Linux: "Wrong JPEG library version: library is 90, caller expects 62"

### ISSUE THREAD

**Issue by FrankEscobar** [mozilla/mozjpeg#408]
I'm using MozJpeg in a windows app without problems but the same code fails on execution (compiles ok) with that error.

Any idea on this? Thank you for your time.

**Comment by kornelski** [comment]
I think MozJPEG doesn't support ABI 9.0, so you've mixed-up the libraries and you're linking with your system's vanilla libjpeg, and not with mozjpeg.

**Comment by FrankEscobar** [comment]
You are right I'm using Qt Creator as IDE and it is reading the system one.

I've changed it to use pure static and now it works on windows ok but in linux it triggers:
`libjpeg-static.a(jcparam.c.o): in function 'jpeg_set_colorspace': first defined here`

I think that Qt Creator (gcc compiler) priorizes that system library and unfortunately I have no idea how to change that!

**Comment by kornelski** [comment]
C doesn't support namespacing, so you can use only one JPEG library in an executable. If your build already links to libjpeg anywhere, it will break MozJPEG.
