### ISSUE TITLE
Release new versions more frequently

### ISSUE THREAD

**Issue by atjn** [mozilla/mozjpeg#422]
Hello :)

AFAIK most projects use the latest tagged version of `mozjpeg`. Because `mozjpeg` hasn't released an update in quite a while, all of these projects are missing out on ~1.5 years of improvements in both `mozjpeg` and `libjpeg-turbo`. Examples: [sharp](https://github.com/lovell/sharp-libvips/blob/a40f861fae54f23d8ea396a483a2d2b93288fc91/build/lin.sh#L96), [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mozjpeg.rb#L4), [slackware](https://github.com/jabolopes/slackbuilds/blob/master/graphics/mozjpeg/mozjpeg.SlackBuild#L46), [winlib](https://github.com/brechtsanders/winlibs_recipes/blob/d0483025e5192c17e9c3137b51fc994234554114/recipes/mozjpeg.winlib#L68).

I even found [a case](https://github.com/kleisauke/wasm-vips/pull/20#pullrequestreview-1068131008) where `libjpeg-turbo` was chosen instead of `mozjpeg` because the latter seemed outdated. I would hate to see that become a trend.

Would it be possible for you to release newer versions more frequently? If you could do a release approximately every 6 months, then I think that would be completely fine.

Thank you! And please let me know if I'm missing something here.

**Comment by kornelski** [comment]
For a long time now I've been using MozJPEG exclusively via [the Rust crate](https://lib.rs/crates/mozjpeg-sys), so I forgot to update this repo.

**Comment by atjn** [comment]
I see. Hopefully we'll all be using Rust crates one day. Until then, thanks for updating the tags!
