### ISSUE TITLE
Jenkins, mac M1 build failed 

### ISSUE THREAD

**Issue by dante01yoon** [mozilla/mozjpeg#426]
Hi, I use [imagemin-mozjpeg](https://github.com/imagemin/imagemin-mozjpeg) version v6.0.0, which has peer dependency mozjpeg ^4.0.0. since mozjpeg version up to 4.1.1, all platform I use to deploy build failed.

here I attatch build fail  face with. 

jenkins: 
```
/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```
m1: 
```
Warning: Error: dyld[18472]: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/user/Desktop/naver-web/cloval-ai-jaewon/node_modules/mozjpeg/vendor/cjpeg
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
```

I notice this problem to https://github.com/imagemin/imagemin-mozjpeg/issues/73.

**Comment by kornelski** [comment]
This project does not support Node.js. Please report any issues to Node package maintainers.

libpng12 is super outdated. Delete everything using it.
