### ISSUE TITLE
More a request than issue.

### ISSUE THREAD

**Issue by stumbles** [mozilla/mozjpeg#428]
How about renaming its executables such cjpeg, etc and its pkgconf files such that they do not stomp on those provided by libjpeg-turbo.

**Comment by zvezdochiot** [comment]
Hi @stumbles .

See #391.

**Comment by kornelski** [comment]
This library is libjpeg-turbo. It contains all of libjpeg-turbo's code and is fully compatible with libjpeg-turbo including ABI. You're supposed to replace/overwrite libjpeg-turbo with it.

**Comment by stumbles** [comment]
BTAIM, no reason to stomp on libjpeg-turbo.

**Comment by kornelski** [comment]
The maintainer of libjpeg-turbo has two priorities: keep it as fast as possible, maintain less. Which is incompatible with mozjpeg's goal of adding extra code that improves compression.

But while priorities of the projects are different, on the technical side they're compatible. If you prefer better compression (with an option to switch back to fastest if needed), then this is the version of libjpeg-turbo you should use.
