### ISSUE TITLE
GUI for mozjpeg

### ISSUE THREAD

**Issue by kowpa1990** [mozilla/mozjpeg#52]
Are you going to create a gui for mozjpeg?
I was thinking about something portable and multi-platform. Maybe simple application, supports the batch conversion, created in the shape of WinFF?
http://winff.org/

**Comment by damian101** [comment]
There is a nice GUI for Windows called mozjpeGUI: [http://s.masayaohara.com](http://s.masayaohara.com)

**Comment by kornelski** [comment]
Also https://squoosh.app or https://imageoptim.com/mozjpeg

**Comment by Every0ne** [comment]
I made one, it's Windows-only though. https://github.com/Every0ne/MozJPEG-GUI
