### ISSUE TITLE
Introduce high quality up-sizing/enlarging

### ISSUE THREAD

**Issue by kowpa1990** [mozilla/mozjpeg#66]
...in cjpeg as a option similar to [-scale](http://jpegclub.org/cjpeg/). In comparison to downsampling, [upsampling](http://blog.codinghorror.com/better-image-resizing/) needs more complexity in the calculations to the picture [looked](http://hermidownloads.craqstar.de/videoresizefiltercomparasion/) [good](http://superuser.com/questions/375718/which-resize-algorithm-to-choose-for-videos). Why use a [magnified images](http://www.wisdom.weizmann.ac.il/~vision/SingleImageSR.html)?
- people use super-resolution (SR) for [print](http://www.ononesoftware.com/products/resize8/)
- in web pages to avoid users scale from low-res interpolation (see also  [image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), 'Gecko uses bilinear resampling'; they call it 'high quality' - there is a lot better scalers)
- for 'recover detail from all kinds of degraded [sources](http://www.fixerlabs.com/EN/news/sizefixer2pp.pdf)'
- for [pseudo-retina](http://filamentgroup.com/lab/compressive-images.html) display on web pages (and when they do not have pictures straight from the source - camera - in hi-res)
- to [zoom worms and insects](http://jonrista.com/2013/12/16/extreme-digital-upscaling/)
- etc.

[NNEDI3](http://forum.doom9.org/showthread.php?t=147695) is the best interpolation algorithm available in Avisynth, and in my opinion lend itself for an extra feature for mozjpeg. In the future, when the [DC Tune](https://github.com/mozilla/mozjpeg/issues/28), [aggressive optimizations](https://github.com/mozilla/mozjpeg/issues/12) find themselves in mozjpeg, it will be a great complement to the high quality resampler via [Retina Revolution](http://users.wfu.edu/matthews/misc/graphics/ResVsComp/JpgResVsComp.html), and competitor for adaptive (edge-detecting) algorithm PhotoZoom.

Why use NNEDI3?
It is regarded by the community dedicated to converting video for the best interpolation algorithm but by the fossilization / orthodoxy / conservatism of the community is not available to a potential audience. Adding it to mozjpeg add freshness to the project.

Someone has [already done](http://jeanbruenn.info/2011/10/30/upscaling-in-avisynth-comparison-of-resizers/) a detailed testcase perfect NNEDI3.

In addition, [a](http://research.microsoft.com/en-us/um/people/kopf/pixelart/supplementary/multi_comparison.html) [few](http://web.archive.org/web/20060827184031/http://www.path.unimelb.edu.au/~dersch/interpolator/interpolator.html) [links](http://www.cambridgeincolour.com/tutorials/image-interpolation.htm) [concerning](http://www.cambridgeincolour.com/tutorials/digital-photo-enlargement.htm) [interpolation](http://www.cambridgeincolour.com/tutorials/image-resize-for-web.htm).

cons NNEDI3:
- enlarging images only by powers of 2

[I made a visual testcase](https://www.dropbox.com/s/92y5vz6x30drgxa/nnedi3_testcase.7z) which takes account of popular interpolation algorithms.
[Screen](https://www.dropbox.com/s/bi0m2yw11xqs35q/screen.jpg)
Inside there's more links regarding upscaling.

**Comment by andrews05** [comment]
@dwbuiten have you submitted a patch to ImageMagick? If not, can you quickly tell how to build it with mozjpeg?
