### ISSUE TITLE
Problem compiling on Ubuntu 12.04

### ISSUE THREAD

**Issue by matylla** [mozilla/mozjpeg#99]
64-bit build on 64-bit Ubuntu 12.04

```
$ sh ../configure
```

```
../configure: line 12975: syntax error near unexpected token `libpng,'
../configure: line 12975: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'
```

Anyone?

**Comment by okor** [comment]
@dwbulten @matylla Could you expand on the solution a bit for us mere mortals? Like if I am `missing the pkg config macros` which I don't really understand what further actions should I take to correct the problem?

Thanks!

**Comment by okor** [comment]
Ok, actually figured this out. For me, I had pkg-config installed already. But I had to do a `sudo ldconfig /usr/lib` since this was a fresh box.

Googlers: Ensure you have all packages installed reload shared libs before attempting to compile. So something like:

```
sudo apt-get -y install build-essential cmake libtool autoconf automake m4 nasm pkg-config
sudo ldconfig /usr/lib
cd ~
wget https://github.com/mozilla/mozjpeg/archive/v3.1.tar.gz
cd mozjpeg-3.1/
autoreconf -fiv
mkdir build
cd build
sh ../configure
sudo make install
```

Works for me.

**Comment by kappuccino** [comment]
thank you @okor for your condensed solution.

**Comment by thegbom** [comment]
sudo apt-get -y install build-essential cmake libtool autoconf automake m4 nasm pkg-config
sudo ldconfig /usr/lib
cd ~
wget https://github.com/mozilla/mozjpeg/archive/v3.1.tar.gz
tar -xvzf v3.1.tar.gz 
cd mozjpeg-3.1/
autoreconf -fiv
mkdir build
cd build
sh ../configure
sudo make install

I supplemented a missing tar-statement. Running npm install after the steps above, I did not get the error.

**Comment by cbj4074** [comment]
Thanks for articulating the solution, @okor (and for providing the missing `tar` step, @thegbom ).

In my particular case, installing `pkg-config` "fixed" the issue, but the more poignant question seems to be, what causes the initial failure that requires building from source at all? This line:

`⚠ The `/var/www/html/laravel/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly`

Why does this `cjpeg` binary not `work correctly` upon installation?

**Comment by kornelski** [comment]
I have no idea why the node module complains. You're asking in the wrong project. The Node.js binary is maintained by https://github.com/imagemin/mozjpeg-bin

**Comment by cbj4074** [comment]
Thanks for clarifying the origin of the problem, @kornelski . I loathe to be the guy who complains to the incorrect project.

It looks like this may be the place to discuss this further:

https://github.com/imagemin/imagemin/issues/168

**Comment by salehawal** [comment]
@dwbuiten it works
i ma using ubuntu
i installed the missing package : sudo apt-get install pkg-config
and then autoreconf -fi and now it is working thanks (:+1:
